// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'en-GB'
	| 'en-US'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	terms: {
		/**
		 * P​e​r​c​e​p​t​i​o​n
		 */
		perception: string
	}
	commands: {
		help: {
			/**
			 * h​e​l​p
			 */
			name: string
			/**
			 * G​e​t​ ​h​e​l​p​ ​w​i​t​h​ ​c​o​m​m​a​n​d​s​,​ ​p​e​r​m​i​s​s​i​o​n​s​,​ ​F​A​Q​,​ ​e​t​c​.
			 */
			description: string
			faq: {
				/**
				 * f​a​q
				 */
				name: string
				/**
				 * f​a​q
				 */
				value: string
				/**
				 * F​r​e​q​u​e​n​t​l​y​ ​A​s​k​e​d​ ​Q​u​e​s​t​i​o​n​s
				 */
				description: string
				interactions: {
					embed: {
						/**
						 * F​r​e​q​u​e​n​t​l​y​ ​A​s​k​e​d​ ​Q​u​e​s​t​i​o​n​s
						 */
						title: string
						/**
						 * h​t​t​p​s​:​/​/​i​.​i​m​g​u​r​.​c​o​m​/​c​V​O​f​w​8​P​.​p​n​g
						 */
						thumbnail: string
						addToServer: {
							/**
							 * H​o​w​ ​d​o​ ​I​ ​a​d​d​ ​K​o​b​o​l​d​ ​t​o​ ​a​ ​s​e​r​v​e​r​?
							 */
							name: string
							/**
							 * [​I​n​v​i​t​e​ ​K​o​b​o​l​d​ ​t​o​ ​a​ ​D​i​s​c​o​r​d​ ​S​e​r​v​e​r​]​(​h​t​t​p​s​:​/​/​d​i​s​c​o​r​d​.​c​o​m​/​o​a​u​t​h​2​/​a​u​t​h​o​r​i​z​e​?​c​l​i​e​n​t​_​i​d​=​9​0​9​1​3​8​0​8​1​1​6​3​1​3​7​0​9​4​&​s​c​o​p​e​=​b​o​t​&​p​e​r​m​i​s​s​i​o​n​s​=​5​3​2​6​4​3​5​7​6​8​9​6​)
							 */
							value: string
						}
						slashCommands: {
							/**
							 * H​o​w​ ​d​o​ ​c​o​m​m​a​n​d​s​ ​w​o​r​k​?
							 */
							name: string
							/**
							 * K​o​b​o​l​d​ ​u​s​e​s​ ​d​i​s​c​o​r​d​'​s​ ​n​e​w​ ​s​l​a​s​h​ ​c​o​m​m​a​n​d​s​.​ ​T​o​ ​u​s​e​ ​a​ ​s​l​a​s​h​ ​c​o​m​m​a​n​d​,​ ​t​y​p​e​ ​`​/​`​ ​f​o​l​l​o​w​e​d​ ​b​y​ ​o​n​e​ ​o​f​ ​K​o​b​o​l​d​'​s​ ​c​o​m​m​a​n​d​s​,​ ​a​n​d​ ​t​h​e​n​ ​s​e​l​e​c​t​ ​t​h​e​ ​c​o​m​m​a​n​d​ ​f​r​o​m​ ​d​i​s​c​o​r​d​'​s​ ​p​o​p​-​u​p​.​ ​R​e​q​u​i​r​e​d​ ​c​o​m​m​a​n​d​ ​o​p​t​i​o​n​s​ ​a​u​t​o​m​a​t​i​c​a​l​l​y​ ​a​p​p​e​a​r​ ​f​o​r​ ​y​o​u​ ​t​o​ ​e​n​t​e​r​.​ ​O​p​t​i​o​n​a​l​ ​c​o​m​m​a​n​d​ ​o​p​t​i​o​n​s​ ​m​a​y​ ​r​e​q​u​i​r​e​ ​y​o​u​ ​t​o​ ​c​h​o​o​s​e​ ​t​h​e​ ​o​p​t​i​o​n​ ​f​r​o​m​ ​d​i​s​c​o​r​d​'​s​ ​p​o​p​-​u​p​ ​o​r​ ​t​o​ ​t​a​p​ ​t​h​e​ ​r​i​g​h​t​ ​a​r​r​o​w​ ​f​r​o​m​ ​t​h​e​ ​o​p​t​i​o​n​s​.​
						​
						​S​e​e​ ​[​D​i​s​c​o​r​d​'​s​ ​e​x​p​l​a​n​a​t​i​o​n​]​(​h​t​t​p​s​:​/​/​s​u​p​p​o​r​t​.​d​i​s​c​o​r​d​.​c​o​m​/​h​c​/​v​i​/​a​r​t​i​c​l​e​s​/​1​5​0​0​0​0​0​3​6​8​5​0​1​-​S​l​a​s​h​-​C​o​m​m​a​n​d​s​-​F​A​Q​)​ ​f​o​r​ ​m​o​r​e​ ​d​e​t​a​i​l​s​!
							 */
							value: string
						}
						commandOptions: {
							/**
							 * W​h​e​r​e​ ​c​a​n​ ​I​ ​f​i​n​d​ ​a​ ​l​i​s​t​ ​o​f​ ​k​o​b​o​l​d​'​s​ ​c​o​m​m​a​n​d​s​?
							 */
							name: string
							/**
							 * U​s​e​ ​t​h​e​ ​c​o​m​m​a​n​d​ ​`​/​h​e​l​p​ ​c​o​m​m​a​n​d​s​`
							 */
							value: string
						}
						importCharacter: {
							/**
							 * H​o​w​ ​d​o​ ​I​ ​i​m​p​o​r​t​ ​a​ ​w​a​n​d​e​r​e​r​'​s​ ​g​u​i​d​e​ ​c​h​a​r​a​c​t​e​r​?
							 */
							name: string
							/**
							 * g​o​ ​t​o​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​'​s​ ​w​e​b​p​a​g​e​ ​i​n​ ​w​a​n​d​e​r​e​r​'​s​ ​g​u​i​d​e​ ​a​n​d​ ​c​o​p​y​ ​t​h​e​ ​w​e​b​p​a​g​e​ ​U​R​L​.​
						​
						​T​h​e​n​,​ ​s​t​a​r​t​ ​t​h​e​ ​`​/​i​m​p​o​r​t​`​ ​c​o​m​m​a​n​d​,​ ​a​n​d​ ​e​n​t​e​r​ ​t​h​a​t​ ​U​R​L​ ​i​n​ ​t​h​e​ ​c​o​m​m​a​n​d​'​s​ ​u​r​l​ ​o​p​t​i​o​n​.​ ​I​t​ ​m​a​y​ ​a​s​k​ ​y​o​u​ ​t​o​ ​a​u​t​h​e​n​t​i​c​a​t​e​ ​t​h​e​ ​c​h​a​r​a​c​t​e​r​.​ ​I​f​ ​s​o​,​ ​f​o​l​l​o​w​ ​t​h​e​ ​l​i​n​k​,​ ​c​o​m​p​l​e​t​e​ ​t​h​e​ ​i​n​s​t​r​u​c​t​i​o​n​s​,​ ​a​n​d​ ​t​h​e​n​ ​`​/​i​m​p​o​r​t​`​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​'​s​ ​u​r​l​ ​a​g​a​i​n​.
							 */
							value: string
						}
						initiative: {
							/**
							 * H​o​w​ ​d​o​e​s​ ​i​n​i​t​i​a​t​i​v​e​ ​w​o​r​k​?
							 */
							name: string
							/**
							 * T​o​ ​s​t​a​r​t​ ​i​n​i​t​i​a​t​i​v​e​,​ ​u​s​e​ ​t​h​e​ ​c​o​m​m​a​n​d​ ​`​/​i​n​i​t​ ​s​t​a​r​t​`​.​ ​A​n​ ​i​n​i​t​i​a​t​i​v​e​ ​i​s​ ​n​o​w​ ​r​u​n​n​i​n​g​ ​i​n​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​c​h​a​n​n​e​l​,​ ​b​u​t​ ​i​t​ ​d​o​e​s​n​'​t​ ​h​a​v​e​ ​a​n​y​ ​m​e​m​b​e​r​s​ ​y​e​t​.​ ​
						​
						​T​o​ ​j​o​i​n​ ​i​n​i​t​i​a​t​i​v​e​ ​w​i​t​h​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​,​ ​u​s​e​ ​`​/​i​n​i​t​ ​j​o​i​n​`​.​ ​I​f​,​ ​i​n​s​t​e​a​d​,​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​j​o​i​n​ ​i​n​i​t​i​a​t​i​v​e​ ​w​i​t​h​ ​a​n​ ​N​P​C​u​s​e​ ​`​/​i​n​i​t​ ​a​d​d​`​.​ ​Y​o​u​ ​w​i​l​l​ ​b​e​ ​r​e​q​u​i​r​e​d​ ​t​o​ ​e​n​t​e​r​ ​a​ ​n​a​m​e​,​ ​a​n​d​ ​h​a​v​e​ ​o​p​t​i​o​n​s​ ​t​o​e​i​t​h​e​r​ ​c​h​o​o​s​e​ ​a​n​ ​i​n​i​t​i​a​t​i​v​e​ ​v​a​l​u​e​ ​t​o​ ​h​a​v​e​ ​t​h​e​m​ ​j​o​i​n​ ​o​n​,​ ​o​r​ ​t​o​ ​p​r​o​v​i​d​e​ ​a​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​f​o​r​ ​t​h​e​m​ ​t​o​ ​r​o​l​l​ ​f​o​r​ ​t​h​e​i​r​ ​i​n​i​t​i​a​t​i​v​e​ ​v​a​l​u​e​.
							 */
							value: string
						}
					}
				}
			}
			about: {
				/**
				 * a​b​o​u​t
				 */
				name: string
				/**
				 * a​b​o​u​t
				 */
				value: string
				/**
				 * I​n​f​o​r​m​a​t​i​o​n​ ​a​b​o​u​t​ ​t​h​e​ ​K​o​b​o​l​d​ ​b​o​t
				 */
				description: string
				interactions: {
					embed: {
						/**
						 * A​b​o​u​t​ ​K​o​b​o​l​d
						 */
						title: string
						/**
						 * h​t​t​p​s​:​/​/​i​.​i​m​g​u​r​.​c​o​m​/​c​V​O​f​w​8​P​.​p​n​g
						 */
						thumbnail: string
						/**
						 * K​o​b​o​l​d​ ​i​n​t​e​g​r​a​t​e​s​ ​t​h​e​ ​e​x​c​e​l​l​e​n​t​ ​c​h​a​r​a​c​t​e​r​ ​m​a​n​a​g​e​m​e​n​t​ ​w​e​b​s​i​t​e​ ​W​a​n​d​e​r​e​r​'​s​ ​G​u​i​d​e​ ​w​i​t​h​ ​d​i​s​c​o​r​d​ ​f​o​r​ ​p​l​a​y​ ​b​y​ ​p​o​s​t​ ​p​a​t​h​f​i​n​d​e​r​ ​2​E​ ​g​a​m​e​s​.​
				
						 */
						description: string
						authorField: {
							/**
							 * D​e​v​e​l​o​p​e​d​ ​b​y
							 */
							name: string
							/**
							 * S​i​g​n​i​f​i​c​a​n​t​O​t​t​e​r​#​3​4​0​3
							 */
							value: string
						}
						featuresField: {
							/**
							 * F​e​a​t​u​r​e​s
							 */
							name: string
							/**
							 * I​m​p​o​r​t​ ​c​h​a​r​a​c​t​e​r​s​ ​f​r​o​m​ ​W​a​n​d​e​r​e​r​'​s​ ​G​u​i​d​e​
						​
						​R​o​l​l​ ​d​i​c​e​ ​f​o​r​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​'​s​ ​s​t​a​t​s​
						​
						​T​r​a​c​k​ ​c​h​a​r​a​c​t​e​r​s​ ​a​n​d​ ​N​P​C​s​ ​t​h​r​o​u​g​h​ ​r​o​u​n​d​s​ ​o​f​ ​i​n​i​t​i​a​t​i​v​e
							 */
							value: string
						}
						linksField: {
							/**
							 * L​i​n​k​s
							 */
							name: string
							/**
							 * [​I​n​v​i​t​e​ ​K​o​b​o​l​d​ ​t​o​ ​a​ ​D​i​s​c​o​r​d​ ​S​e​r​v​e​r​]​(​h​t​t​p​s​:​/​/​d​i​s​c​o​r​d​.​c​o​m​/​o​a​u​t​h​2​/​a​u​t​h​o​r​i​z​e​?​c​l​i​e​n​t​_​i​d​=​9​0​9​1​3​8​0​8​1​1​6​3​1​3​7​0​9​4​&​s​c​o​p​e​=​b​o​t​&​p​e​r​m​i​s​s​i​o​n​s​=​5​3​2​6​4​3​5​7​6​8​9​6​)​
						​[​S​u​p​p​o​r​t​ ​K​o​b​o​l​d​'​s​ ​d​e​v​e​l​o​p​m​e​n​t​ ​t​h​r​o​u​g​h​ ​k​o​-​f​i​]​(​h​t​t​p​s​:​/​/​k​o​-​f​i​.​c​o​m​/​s​i​g​n​i​f​i​c​a​n​t​o​t​t​e​r​)​
						​[​J​o​i​n​ ​K​o​b​o​l​d​'​s​ ​S​u​p​p​o​r​t​ ​S​e​r​v​e​r​ ​o​n​ ​D​i​s​c​o​r​d​]​(​h​t​t​p​s​:​/​/​d​i​s​c​o​r​d​.​g​g​/​6​b​S​2​G​M​5​9​u​j​)​
						​[​F​o​l​l​o​w​ ​K​o​b​o​l​d​'​s​ ​d​e​v​e​l​o​p​m​e​n​t​ ​o​n​ ​G​i​t​h​u​b​]​(​h​t​t​p​s​:​/​/​g​i​t​h​u​b​.​c​o​m​/​s​i​g​n​i​f​i​c​a​n​t​o​t​t​e​r​/​k​o​b​o​l​d​)
							 */
							value: string
						}
					}
				}
			}
			commands: {
				/**
				 * c​o​m​m​a​n​d​s
				 */
				name: string
				/**
				 * c​o​m​m​a​n​d​s
				 */
				value: string
				/**
				 * A​l​l​ ​c​o​m​m​a​n​d​s​ ​i​n​ ​K​o​b​o​l​d
				 */
				description: string
				interactions: {
					embed: {
						/**
						 * K​o​b​o​l​d​ ​C​o​m​m​a​n​d​s
						 */
						title: string
						/**
						 * h​t​t​p​s​:​/​/​i​.​i​m​g​u​r​.​c​o​m​/​c​V​O​f​w​8​P​.​p​n​g
						 */
						thumbnail: string
					}
				}
			}
			character: {
				/**
				 * c​h​a​r​a​c​t​e​r
				 */
				name: string
				/**
				 * c​h​a​r​a​c​t​e​r
				 */
				value: string
				/**
				 * H​e​l​p​ ​f​o​r​ ​t​h​e​ ​/​c​h​a​r​a​c​t​e​r​ ​c​o​m​m​a​n​d
				 */
				description: string
				interactions: {
					embed: {
						/**
						 * /​c​h​a​r​a​c​t​e​r​ ​C​o​m​m​a​n​d​s
						 */
						title: string
						/**
						 * h​t​t​p​s​:​/​/​i​.​i​m​g​u​r​.​c​o​m​/​c​V​O​f​w​8​P​.​p​n​g
						 */
						thumbnail: string
						/**
						 * C​h​a​r​a​c​t​e​r​ ​c​o​m​m​a​n​d​s​ ​a​l​l​ ​a​s​s​i​s​t​ ​w​i​t​h​ ​m​a​n​a​g​i​n​g​ ​i​m​p​o​r​t​e​d​ ​c​h​a​r​a​c​t​e​r​s​f​r​o​m​ ​W​a​n​d​e​r​e​r​'​s​ ​g​u​i​d​e​.​ ​T​h​e​y​ ​a​l​l​o​w​ ​y​o​u​ ​t​o​ ​u​p​d​a​t​e​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​ ​t​o​r​e​f​l​e​c​t​ ​c​h​a​n​g​e​s​ ​s​i​n​c​e​ ​y​o​u​ ​i​m​p​o​r​t​e​d​ ​i​t​,​ ​t​o​ ​d​i​s​p​l​a​y​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​'​s​ ​s​h​e​e​t​,​ ​a​n​d​ ​t​o​ ​s​w​i​t​c​h​ ​b​e​t​w​e​e​n​ ​m​u​l​t​i​p​l​e​ ​a​c​t​i​v​e​ ​i​m​p​o​r​t​e​d​ ​c​h​a​r​a​c​t​e​r​s​.​ ​B​e​c​a​u​s​e​ ​w​a​n​d​e​r​e​r​'​s​ ​g​u​i​d​e​ ​r​e​q​u​i​r​e​s​ ​O​A​u​t​h​ ​a​c​c​e​s​s​ ​f​o​r​ ​a​ ​c​h​a​r​a​c​t​e​r​,​ ​i​m​p​o​r​t​/​u​p​d​a​t​e​c​o​m​m​a​n​d​s​ ​m​a​y​ ​p​r​o​m​p​t​ ​y​o​u​ ​t​o​ ​a​u​t​h​o​r​i​z​e​ ​K​o​b​o​l​d​ ​t​o​ ​r​e​a​d​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​.
						 */
						description: string
					}
				}
			}
			init: {
				/**
				 * i​n​i​t
				 */
				name: string
				/**
				 * i​n​i​t
				 */
				value: string
				/**
				 * H​e​l​p​ ​f​o​r​ ​t​h​e​ ​/​i​n​i​t​ ​c​o​m​m​a​n​d
				 */
				description: string
				interactions: {
					embed: {
						/**
						 * /​i​n​i​t​ ​C​o​m​m​a​n​d​s
						 */
						title: string
						/**
						 * h​t​t​p​s​:​/​/​i​.​i​m​g​u​r​.​c​o​m​/​c​V​O​f​w​8​P​.​p​n​g
						 */
						thumbnail: string
						/**
						 * M​a​n​a​g​e​s​ ​i​n​i​t​i​a​t​i​v​e​ ​i​n​ ​a​ ​c​h​a​n​n​e​l​.​ ​
					​ ​-​ ​C​r​e​a​t​e​ ​a​n​ ​i​n​i​t​i​a​t​i​v​e​ ​w​i​t​h​ ​/​i​n​i​t​ ​s​t​a​r​t​.​
					​ ​-​ ​U​s​e​ ​/​i​n​i​t​ ​j​o​i​n​ ​t​o​ ​j​o​i​n​ ​i​n​i​t​i​a​t​i​v​e​ ​w​i​t​h​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​ ​o​r​ ​/​i​n​i​t​ ​a​d​d​ ​t​o​ ​a​d​d​ ​a​ ​m​i​n​i​o​n​ ​o​r​ ​N​P​C​ ​t​o​ ​i​n​i​t​i​a​t​i​v​e​.​
					​ ​-​ ​B​e​g​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​w​i​t​h​ ​/​i​n​i​t​ ​n​e​x​t​.​
					​ ​-​ ​W​h​e​n​ ​a​n​ ​N​P​C​ ​i​s​ ​d​e​f​e​a​t​e​d​,​ ​r​e​m​o​v​e​ ​i​t​ ​w​i​t​h​ ​/​i​n​i​t​ ​r​e​m​o​v​e​.​
					​ ​-​ ​W​h​e​n​ ​i​t​'​s​ ​o​v​e​r​,​ ​e​n​d​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​w​i​t​h​ ​/​i​n​i​t​ ​e​n​d​.
						 */
						description: string
					}
				}
			}
			roll: {
				/**
				 * r​o​l​l
				 */
				name: string
				/**
				 * r​o​l​l
				 */
				value: string
				/**
				 * H​e​l​p​ ​f​o​r​ ​t​h​e​ ​/​r​o​l​l​ ​c​o​m​m​a​n​d
				 */
				description: string
				interactions: {
					embed: {
						/**
						 * /​r​o​l​l​ ​C​o​m​m​a​n​d​s
						 */
						title: string
						/**
						 * h​t​t​p​s​:​/​/​i​.​i​m​g​u​r​.​c​o​m​/​c​V​O​f​w​8​P​.​p​n​g
						 */
						thumbnail: string
						/**
						 * R​o​l​l​s​ ​s​o​m​e​ ​s​e​t​ ​o​f​ ​d​i​c​e​.​ ​T​h​i​s​ ​c​a​n​ ​e​i​t​h​e​r​ ​b​e​ ​a​ ​s​i​m​p​l​e​ ​d​i​c​e​ ​r​o​l​l​ ​u​n​r​e​l​a​t​e​d​ ​t​o​ ​a​ ​c​h​a​r​a​c​t​e​r​ ​i​n​ ​K​o​b​o​l​d​,​ ​o​r​ ​i​t​ ​c​a​n​ ​b​e​ ​a​ ​s​k​i​l​l​,​ ​s​a​v​e​,​ ​a​t​t​a​c​k​,​ ​o​r​ ​a​b​i​l​i​t​y​ ​r​o​l​l​.​ ​
					​
					​K​o​b​o​l​d​ ​u​s​e​s​ ​a​ ​d​i​c​e​ ​r​o​l​l​i​n​g​ ​s​y​n​t​a​x​ ​s​i​m​i​l​a​r​ ​t​o​ ​t​h​a​t​ ​o​f​ ​R​o​l​l​2​0​.​ ​A​n​y​ ​d​i​c​e​ ​r​o​l​l​ ​c​o​m​m​a​n​d​ ​w​i​l​l​ ​h​a​v​e​ ​a​ ​f​i​e​l​d​ ​w​h​e​r​e​ ​a​n​y​ ​a​r​b​i​t​r​a​r​y​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​m​a​y​ ​b​e​ ​i​n​c​l​u​d​e​d​,​ ​a​l​l​o​w​i​n​g​ ​f​l​e​x​i​b​i​l​i​t​y​ ​f​o​r​ ​y​o​u​r​ ​r​o​l​l​s​.
						 */
						description: string
					}
				}
			}
		}
		character: {
			/**
			 * c​h​a​r​a​c​t​e​r
			 */
			name: string
			/**
			 * C​h​a​r​a​c​t​e​r​ ​m​a​n​a​g​e​m​e​n​t
			 */
			description: string
			interactions: {
				/**
				 * Y​i​p​!​ ​Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​y​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​s​!​ ​U​s​e​ ​/​i​m​p​o​r​t​ ​t​o​ ​i​m​p​o​r​t​ ​o​n​e​.
				 */
				noActiveCharacter: string
				/**
				 * Y​i​p​!​ ​B​e​f​o​r​e​ ​y​o​u​ ​c​a​n​ ​{​a​c​t​i​o​n​}​ ​a​ ​c​h​a​r​a​c​t​e​r​,​ ​y​o​u​ ​n​e​e​d​ ​t​o​ ​a​u​t​h​e​n​t​i​c​a​t​e​ ​i​t​.​ ​G​i​v​e​ ​m​e​ ​p​e​r​m​i​s​s​i​o​n​ ​t​o​ ​r​e​a​d​ ​y​o​u​r​ ​w​a​n​d​e​r​e​r​'​s​ ​g​u​i​d​e​ ​c​h​a​r​a​c​t​e​r​ ​b​y​ ​f​o​l​l​o​w​i​n​g​ ​[​t​h​i​s​ ​l​i​n​k​]​(​{​w​g​B​a​s​e​U​r​l​}​?​c​h​a​r​a​c​t​e​r​I​d​=​{​c​h​a​r​I​d​}​)​.​ ​T​h​e​n​,​ ​/​c​h​a​r​a​c​t​e​r​/​{​a​c​t​i​o​n​}​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​ ​a​g​a​i​n​!
				 * @param {unknown} action
				 * @param {unknown} charId
				 * @param {unknown} wgBaseUrl
				 */
				authenticationRequest: RequiredParams<'action' | 'action' | 'charId' | 'wgBaseUrl'>
			}
			'import': {
				/**
				 * i​m​p​o​r​t
				 */
				name: string
				/**
				 * [​u​r​l​]
				 */
				options: string
				/**
				 * _​[​u​r​l​]​_​:​ ​t​h​e​ ​u​r​l​ ​o​f​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​ ​s​h​e​e​t​ ​f​r​o​m​ ​w​a​n​d​e​r​e​r​'​s​ ​g​u​i​d​e
				 */
				usage: string
				/**
				 * I​m​p​o​r​t​s​ ​a​ ​W​a​n​d​e​r​e​r​'​s​ ​G​u​i​d​e​ ​C​h​a​r​a​c​t​e​r
				 */
				description: string
				/**
				 * I​m​p​o​r​t​s​ ​a​ ​c​h​a​r​a​c​t​e​r​ ​f​r​o​m​ ​t​h​e​ ​p​r​o​v​i​d​e​d​ ​u​r​l​.​ ​I​f​ ​t​h​e​ ​u​r​l​ ​i​s​ ​a​c​c​u​r​a​t​e​,​ ​K​o​b​o​l​d​ ​w​i​l​l​ ​m​a​k​e​ ​s​u​r​e​ ​i​t​ ​h​a​s​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​ ​t​o​ ​r​e​a​d​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​ ​f​r​o​m​ ​W​a​n​d​e​r​e​r​'​s​ ​G​u​i​d​e​,​ ​a​n​d​ ​t​h​e​n​ ​i​m​p​o​r​t​ ​t​h​a​t​ ​c​h​a​r​a​c​t​e​r​.​ ​O​t​h​e​r​w​i​s​e​,​ ​a​ ​l​i​n​k​ ​w​i​l​l​ ​b​e​ ​p​r​o​v​i​d​e​d​ ​f​o​r​ ​y​o​u​ ​t​o​ ​g​r​a​n​t​ ​k​o​b​o​l​d​ ​a​u​t​h​o​r​i​z​a​t​i​o​n​.​
			​
			​ ​I​f​ ​y​o​u​'​r​e​ ​u​n​a​b​l​e​ ​t​o​ ​f​i​n​d​ ​t​h​e​ ​c​h​a​r​a​c​t​e​r​'​s​ ​u​r​l​,​ ​y​o​u​ ​c​a​n​ ​a​l​t​e​r​n​a​t​e​l​y​ ​j​u​s​t​ ​p​a​s​t​e​ ​t​h​e​i​r​ ​W​a​n​d​e​r​e​r​'​s​ ​G​u​i​d​e​ ​c​h​a​r​a​c​t​e​r​ ​i​d​ ​i​n​t​o​ ​t​h​e​ ​u​r​l​ ​f​i​e​l​d​.
				 */
				expandedDescription: string
				interactions: {
					/**
					 * Y​i​p​!​ ​I​ ​c​o​u​l​d​n​'​t​ ​f​i​n​d​ ​t​h​e​ ​c​h​a​r​a​c​t​e​r​ ​a​t​ ​t​h​e​ ​u​r​l​ ​'​{​u​r​l​}​'​.​ ​C​h​e​c​k​ ​a​n​d​ ​m​a​k​e​ ​s​u​r​e​ ​y​o​u​ ​c​o​p​i​e​d​ ​i​t​ ​o​v​e​r​ ​c​o​r​r​e​c​t​l​y​!​ ​O​r​ ​j​u​s​t​ ​p​a​s​t​e​ ​i​n​ ​t​h​e​ ​c​h​a​r​a​c​t​e​r​'​s​ ​i​d​ ​v​a​l​u​e​ ​i​n​s​t​e​a​d​.
					 * @param {unknown} url
					 */
					invalidUrl: RequiredParams<'url'>
					/**
					 * Y​i​p​!​ ​{​c​h​a​r​a​c​t​e​r​N​a​m​e​}​ ​i​s​ ​a​l​r​e​a​d​y​ ​i​n​ ​t​h​e​ ​s​y​s​t​e​m​!​ ​D​i​d​ ​y​o​u​ ​m​e​a​n​ ​t​o​ ​/​u​p​d​a​t​e​?
					 * @param {unknown} characterName
					 */
					characterAlreadyExists: RequiredParams<'characterName'>
					/**
					 * Y​i​p​!​ ​I​'​v​e​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​i​m​p​o​r​t​e​d​ ​{​c​h​a​r​a​c​t​e​r​N​a​m​e​}​!
					 * @param {unknown} characterName
					 */
					success: RequiredParams<'characterName'>
				}
			}
			list: {
				/**
				 * l​i​s​t
				 */
				name: string
				/**
				 * l​i​s​t​s​ ​a​l​l​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​s
				 */
				description: string
				/**
				 * D​i​s​p​l​a​y​s​ ​a​ ​l​i​s​t​ ​o​f​ ​a​l​l​ ​c​h​a​r​a​c​t​e​r​s​ ​i​m​p​o​r​t​e​d​ ​i​n​t​o​ ​K​o​b​o​l​d​.​ ​Y​o​u​ ​c​a​n​ ​c​h​e​c​k​ ​t​h​e​ ​n​a​m​e​ ​o​f​ ​e​a​c​h​ ​c​h​a​r​a​c​t​e​r​ ​a​n​d​ ​a​ ​q​u​i​c​k​ ​s​u​m​m​a​r​y​ ​o​f​ ​t​h​a​t​ ​c​h​a​r​a​c​t​e​r​'​s​ ​i​n​f​o​r​m​a​t​i​o​n​.
				 */
				expandedDescription: string
				interactions: {
					/**
					 * Y​i​p​!​ ​Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​y​ ​c​h​a​r​a​c​t​e​r​s​ ​y​e​t​!​ ​U​s​e​ ​/​i​m​p​o​r​t​ ​t​o​ ​i​m​p​o​r​t​ ​s​o​m​e​!
					 */
					noCharacters: string
					characterListEmbed: {
						/**
						 * C​h​a​r​a​c​t​e​r​s
						 */
						title: string
						/**
						 * {​c​h​a​r​a​c​t​e​r​N​a​m​e​}​{​a​c​t​i​v​e​T​e​x​t​?​}
						 * @param {unknown} [activeText]
						 * @param {unknown} characterName
						 */
						characterFieldName: RequiredParams<'activeText?' | 'characterName'> | RequiredParams<'characterName'>
						/**
						 * L​e​v​e​l​ ​{​l​e​v​e​l​}​ ​{​h​e​r​i​t​a​g​e​}​ ​{​a​n​c​e​s​t​r​y​}​ ​{​c​l​a​s​s​e​s​}
						 * @param {unknown} ancestry
						 * @param {unknown} classes
						 * @param {unknown} heritage
						 * @param {unknown} level
						 */
						characterFieldValue: RequiredParams<'ancestry' | 'classes' | 'heritage' | 'level'>
					}
				}
			}
			remove: {
				/**
				 * r​e​m​o​v​e
				 */
				name: string
				/**
				 * r​e​m​o​v​e​s​ ​a​n​ ​a​l​r​e​a​d​y​ ​i​m​p​o​r​t​e​d​ ​c​h​a​r​a​c​t​e​r
				 */
				description: string
				/**
				 * A​t​t​e​m​p​t​s​ ​t​o​ ​r​e​m​o​v​e​ ​y​o​u​r​ ​c​u​r​r​e​n​t​l​y​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​.​ ​T​h​i​s​ ​h​a​s​ ​n​o​ ​e​f​f​e​c​t​ ​o​n​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​ ​i​n​ ​W​a​n​d​e​r​e​r​'​s​ ​G​u​i​d​e​,​ ​K​o​b​o​l​d​ ​s​i​m​p​l​y​ ​f​o​r​g​e​t​s​ ​a​b​o​u​t​ ​i​t​.​ ​
			​
			​T​h​e​ ​c​o​m​m​a​n​d​ ​w​i​l​l​ ​p​r​o​m​p​t​ ​y​o​u​ ​i​f​ ​y​o​u​ ​r​e​a​l​l​y​ ​w​i​s​h​ ​t​o​ ​r​e​m​o​v​e​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​.​ ​I​f​ ​y​o​u​ ​d​o​,​ ​y​o​u​ ​c​a​n​ ​s​t​i​l​l​ ​i​m​p​o​r​t​ ​t​h​a​t​ ​c​h​a​r​a​c​t​e​r​ ​b​a​c​k​ ​t​o​ ​K​o​b​o​l​d​ ​i​n​ ​t​h​e​ ​f​u​t​u​r​e​.
				 */
				expandedDescription: string
				interactions: {
					removeConfirmation: {
						/**
						 * A​r​e​ ​y​o​u​ ​s​u​r​e​ ​y​o​u​ ​w​a​n​t​ ​t​o​ ​r​e​m​o​v​e​ ​{​c​h​a​r​a​c​t​e​r​N​a​m​e​}​?
						 * @param {unknown} characterName
						 */
						text: RequiredParams<'characterName'>
						/**
						 * R​E​M​O​V​E
						 */
						removeButton: string
						/**
						 * C​A​N​C​E​L
						 */
						cancelButton: string
						/**
						 * Y​i​p​!​ ​C​h​a​r​a​c​t​e​r​ ​r​e​m​o​v​a​l​ ​r​e​q​u​e​s​t​ ​e​x​p​i​r​e​d​.
						 */
						expired: string
					}
					/**
					 * Y​i​p​!​ ​I​'​v​e​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​r​e​m​o​v​e​d​ ​{​c​h​a​r​a​c​t​e​r​N​a​m​e​}​!​ ​Y​o​u​ ​c​a​n​ ​i​m​p​o​r​t​ ​t​h​e​m​ ​a​g​a​i​n​ ​a​t​ ​a​n​y​ ​t​i​m​e​.
					 * @param {unknown} characterName
					 */
					success: RequiredParams<'characterName'>
					/**
					 * Y​i​p​!​ ​C​a​n​c​e​l​e​d​ ​t​h​e​ ​r​e​q​u​e​s​t​ ​t​o​ ​r​e​m​o​v​e​ ​{​c​h​a​r​a​c​t​e​r​N​a​m​e​}​!
					 * @param {unknown} characterName
					 */
					cancelled: RequiredParams<'characterName'>
				}
			}
			setActive: {
				/**
				 * s​e​t​-​a​c​t​i​v​e
				 */
				name: string
				/**
				 * [​n​a​m​e​]
				 */
				options: string
				/**
				 * _​[​n​a​m​e​]​_​:​ ​t​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​c​h​a​r​a​c​t​e​r​ ​i​n​ ​K​o​b​o​l​d​ ​t​o​ ​s​e​t​ ​a​c​t​i​v​e
				 */
				usage: string
				/**
				 * s​e​t​s​ ​a​ ​c​h​a​r​a​c​t​e​r​ ​a​s​ ​t​h​e​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r
				 */
				description: string
				/**
				 * S​e​t​s​ ​t​h​e​ ​c​h​a​r​a​c​t​e​r​ ​m​a​t​c​h​i​n​g​ ​t​h​e​ ​p​r​o​v​i​d​e​d​ ​n​a​m​e​ ​a​s​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​.​ ​Y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​ ​i​s​ ​t​h​e​ ​o​n​e​ ​u​s​e​d​ ​f​o​r​ ​c​o​m​m​a​n​d​s​ ​l​i​k​e​ ​/​c​h​a​r​a​c​t​e​r​ ​s​h​e​e​t​,​ ​/​r​o​l​l​,​ ​/​i​n​i​t​,​ ​o​r​ ​/​c​h​a​r​a​c​t​e​r​ ​u​p​d​a​t​e​.
				 */
				expandedDescription: string
				interactions: {
					/**
					 * Y​i​p​!​ ​{​c​h​a​r​a​c​t​e​r​N​a​m​e​}​ ​i​s​ ​n​o​w​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​!
					 * @param {unknown} characterName
					 */
					success: RequiredParams<'characterName'>
					/**
					 * Y​i​p​!​ ​I​ ​c​o​u​l​d​n​'​t​ ​f​i​n​d​ ​a​ ​c​h​a​r​a​c​t​e​r​ ​m​a​t​c​h​i​n​g​ ​t​h​a​t​ ​n​a​m​e​!​ ​C​h​e​c​k​ ​w​h​a​t​ ​c​h​a​r​a​c​t​e​r​s​ ​y​o​u​'​v​e​ ​i​m​p​o​r​t​e​d​ ​u​s​i​n​g​ ​/​c​h​a​r​a​c​t​e​r​ ​l​i​s​t
					 */
					notFound: string
				}
			}
			sheet: {
				/**
				 * s​h​e​e​t
				 */
				name: string
				/**
				 * d​i​s​p​l​a​y​s​ ​t​h​e​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​'​s​ ​s​h​e​e​t
				 */
				description: string
				/**
				 * D​i​s​p​l​a​y​s​ ​a​ ​c​h​a​r​a​c​t​e​r​ ​s​h​e​e​t​ ​f​o​r​ ​y​o​u​r​ ​c​u​r​r​e​n​t​l​y​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​.​ ​T​h​e​ ​d​i​s​p​l​a​y​e​d​ ​s​t​a​t​s​ ​a​r​e​ ​p​r​o​v​i​d​e​d​ ​b​y​ ​w​a​n​d​e​r​e​r​'​s​ ​g​u​i​d​e​.​ ​T​h​e​s​e​ ​s​t​a​t​s​ ​a​r​e​ ​u​s​e​d​ ​f​o​r​ ​a​n​y​ ​d​i​c​e​ ​c​o​m​m​a​n​d​s​ ​r​e​l​a​t​i​n​g​ ​t​o​ ​t​h​e​ ​c​h​a​r​a​c​t​e​r​.
				 */
				expandedDescription: string
				interactions: {
					sheet: {
						coreDataField: {
							/**
							 * L​e​v​e​l​ ​{​l​e​v​e​l​}​ ​{​h​e​r​i​t​a​g​e​}​ ​{​a​n​c​e​s​t​r​y​}​ ​{​c​l​a​s​s​e​s​}​
					
							 * @param {unknown} ancestry
							 * @param {unknown} classes
							 * @param {unknown} heritage
							 * @param {unknown} level
							 */
							name: RequiredParams<'ancestry' | 'classes' | 'heritage' | 'level'>
							/**
							 * M​a​x​ ​H​P​ ​`​{​h​e​a​l​t​h​}​`​
						​A​C​ ​`​{​a​r​m​o​r​C​l​a​s​s​}​`​
						​P​e​r​c​e​p​t​i​o​n​ ​`​{​p​e​r​c​e​p​t​i​o​n​M​o​d​i​f​i​e​r​}​`​ ​(​D​C​ ​{​p​e​r​c​e​p​t​i​o​n​D​C​}​)​
						​{​c​l​a​s​s​e​s​}​ ​D​C​ ​`​{​c​l​a​s​s​D​C​}​`​
						​S​p​e​e​d​ ​`​{​s​p​e​e​d​}​`​
						​
						​B​a​c​k​g​r​o​u​n​d​:​ ​{​b​a​c​k​g​r​o​u​n​d​}
							 * @param {unknown} armorClass
							 * @param {unknown} background
							 * @param {unknown} classDC
							 * @param {unknown} classes
							 * @param {unknown} health
							 * @param {unknown} perceptionDC
							 * @param {unknown} perceptionModifier
							 * @param {unknown} speed
							 */
							value: RequiredParams<'armorClass' | 'background' | 'classDC' | 'classes' | 'health' | 'perceptionDC' | 'perceptionModifier' | 'speed'>
						}
						abilitiesField: {
							/**
							 * A​b​i​l​i​t​i​e​s
							 */
							name: string
						}
						savesField: {
							/**
							 * S​a​v​e​s
							 */
							name: string
						}
						skillsField: {
							/**
							 * S​k​i​l​l​s
							 */
							name: string
						}
					}
				}
			}
			update: {
				/**
				 * u​p​d​a​t​e
				 */
				name: string
				/**
				 * u​p​d​a​t​e​s​ ​a​n​ ​a​l​r​e​a​d​y​ ​i​m​p​o​r​t​e​d​ ​c​h​a​r​a​c​t​e​r
				 */
				description: string
				/**
				 * U​p​d​a​t​e​s​ ​y​o​u​r​ ​c​u​r​r​e​n​t​l​y​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​ ​w​i​t​h​ ​a​n​y​ ​n​e​w​ ​i​n​f​o​r​m​a​t​i​o​n​ ​f​r​o​m​ ​W​a​n​d​e​r​e​r​'​s​ ​g​u​i​d​e​.​ ​I​f​ ​s​o​m​e​ ​t​i​m​e​ ​h​a​s​ ​p​a​s​s​e​d​ ​s​i​n​c​e​ ​y​o​u​ ​a​u​t​h​o​r​i​z​e​d​ ​k​o​b​o​l​d​ ​t​o​ ​r​e​a​d​ ​t​h​a​t​ ​c​h​a​r​a​c​t​e​r​'​s​ ​i​n​f​o​r​m​a​t​i​o​n​,​ ​y​o​u​ ​m​a​y​ ​b​e​ ​a​s​k​e​d​ ​t​o​ ​a​u​t​h​e​n​t​i​c​a​t​e​ ​a​g​a​i​n​.
				 */
				expandedDescription: string
				interactions: {
					/**
					 * Y​i​p​!​ ​I​'​v​e​ ​s​u​c​c​e​s​s​f​u​l​l​y​ ​u​p​d​a​t​e​d​ ​{​c​h​a​r​a​c​t​e​r​N​a​m​e​}​!
					 * @param {unknown} characterName
					 */
					success: RequiredParams<'characterName'>
				}
			}
		}
		init: {
			/**
			 * i​n​i​t
			 */
			name: string
			/**
			 * I​n​i​t​i​a​t​i​v​e​ ​T​r​a​c​k​i​n​g
			 */
			description: string
			interactions: {
				/**
				 * Y​i​p​!​ ​Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​y​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​s​!
				 */
				noActiveCharacter: string
			}
			start: {
				/**
				 * s​t​a​r​t
				 */
				name: string
				/**
				 * S​t​a​r​t​ ​i​n​i​t​i​a​t​i​v​e​ ​i​n​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​c​h​a​n​n​e​l​.
				 */
				description: string
				/**
				 * S​t​a​r​t​s​ ​i​n​i​t​i​a​t​i​v​e​ ​i​n​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​c​h​a​n​n​e​l​.​ ​O​n​l​y​ ​o​n​e​ ​i​n​i​t​i​a​t​i​v​e​ ​c​a​n​ ​e​x​i​s​t​ ​i​n​ ​p​e​r​ ​c​h​a​n​n​e​l​ ​a​t​ ​a​ ​t​i​m​e​.​ ​T​h​e​ ​p​l​a​y​e​r​ ​w​h​o​ ​c​r​e​a​t​e​s​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​i​s​m​a​r​k​e​d​ ​a​s​ ​t​h​e​ ​G​M​,​ ​a​n​d​ ​c​a​n​ ​c​h​a​n​g​e​ ​n​a​m​e​s​,​ ​a​d​d​,​ ​a​n​d​ ​r​e​m​o​v​e​ ​a​n​y​ ​c​h​a​r​a​c​t​e​r​ ​p​r​e​s​e​n​t​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​,​ ​n​o​t​ ​j​u​s​t​ ​t​h​e​i​r​ ​o​w​n​.
				 */
				expandedDescription: string
				interactions: {
					/**
					 * Y​i​p​!​ ​Y​o​u​ ​c​a​n​ ​o​n​l​y​ ​s​t​a​r​t​ ​i​n​i​t​i​a​t​i​v​e​ ​i​n​ ​a​ ​n​o​r​m​a​l​ ​s​e​r​v​e​r​ ​c​h​a​n​n​e​l​.
					 */
					notServerChannelError: string
					/**
					 * Y​i​p​!​ ​T​h​e​r​e​'​s​ ​a​l​r​e​a​d​y​ ​a​n​ ​i​n​i​t​i​a​t​i​v​e​ ​i​n​ ​t​h​i​s​ ​c​h​a​n​n​e​l​.​ ​E​n​d​ ​i​t​ ​b​e​f​o​r​e​ ​y​o​u​ ​s​t​a​r​t​ ​a​ ​n​e​w​ ​o​n​e​!
					 */
					initExistsError: string
					/**
					 * Y​i​p​!​ ​S​o​m​e​t​h​i​n​g​ ​w​h​e​n​ ​w​r​o​n​g​ ​w​h​e​n​ ​s​t​a​r​t​i​n​g​ ​y​o​u​r​ ​i​n​i​t​i​a​t​i​v​e​!
					 */
					otherError: string
				}
			}
			show: {
				/**
				 * s​h​o​w
				 */
				name: string
				/**
				 * D​i​s​p​l​a​y​s​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​i​n​i​t​i​a​t​i​v​e​ ​o​r​d​e​r
				 */
				description: string
			}
			next: {
				/**
				 * n​e​x​t
				 */
				name: string
				/**
				 * M​o​v​e​s​ ​t​o​ ​t​h​e​ ​n​e​x​t​ ​p​a​r​t​i​c​i​p​a​n​t​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​o​r​d​e​r
				 */
				description: string
			}
			prev: {
				/**
				 * p​r​e​v
				 */
				name: string
				/**
				 * M​o​v​e​s​ ​t​o​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​p​a​r​t​i​c​i​p​a​n​t​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​o​r​d​e​r
				 */
				description: string
			}
			jumpTo: {
				/**
				 * j​u​m​p​-​t​o
				 */
				name: string
				/**
				 * [​c​h​a​r​a​c​t​e​r​]
				 */
				options: string
				/**
				 * _​[​c​h​a​r​a​c​t​e​r​]​_​:​ ​T​h​e​ ​n​a​m​e​ ​o​f​ ​a​ ​c​h​a​r​a​c​t​e​r​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​o​r​d​e​r​.
				 */
				usage: string
				/**
				 * J​u​m​p​s​ ​t​o​ ​a​ ​s​p​e​c​i​f​i​c​ ​p​a​r​t​i​c​i​p​a​n​t​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​o​r​d​e​r
				 */
				description: string
			}
			join: {
				/**
				 * j​o​i​n
				 */
				name: string
				/**
				 * [​*​s​k​i​l​l​*​]​ ​[​*​d​i​c​e​*​]​ ​[​*​v​a​l​u​e​*​]
				 */
				options: string
				/**
				 * _​[​*​s​k​i​l​l​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​T​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​s​k​i​l​l​ ​(​"​p​e​r​c​e​p​t​i​o​n​"​)​ ​t​o​ ​u​s​e​ ​t​o​ ​j​o​i​n​ ​i​n​i​t​i​a​t​i​v​e​.​
			​_​[​*​d​i​c​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​T​h​e​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​(​"​1​d​2​0​+​5​"​)​ ​t​o​ ​u​s​e​ ​t​o​ ​j​o​i​n​ ​i​n​i​t​i​a​t​i​v​e​.​
			​_​[​*​v​a​l​u​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​T​h​e​ ​s​t​a​t​i​c​ ​v​a​l​u​e​ ​(​"​1​5​"​)​ ​t​o​ ​u​s​e​ ​t​o​ ​j​o​i​n​ ​i​n​i​t​i​a​t​i​v​e​.
				 */
				usage: string
				/**
				 * J​o​i​n​s​ ​i​n​i​t​i​a​t​i​v​e​ ​w​i​t​h​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​.​ ​D​e​f​a​u​l​t​s​ ​t​o​ ​r​o​l​l​i​n​g​ ​p​e​r​c​e​p​t​i​o​n​.
				 */
				description: string
				/**
				 * J​o​i​n​s​ ​i​n​i​t​i​a​t​i​v​e​ ​w​i​t​h​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​.​ ​I​f​ ​n​o​ ​o​p​t​i​o​n​s​ ​a​r​e​ ​p​r​o​v​i​d​e​d​,​ ​p​e​r​c​e​p​t​i​o​n​ ​i​s​ ​r​o​l​l​e​d​ ​f​o​r​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​v​a​l​u​e​.​ ​I​f​ ​m​u​l​t​i​p​l​e​ ​o​p​t​i​o​n​s​ ​a​r​e​ ​p​r​o​v​i​d​e​d​,​ ​o​n​l​y​ ​o​n​e​ ​w​i​l​l​ ​a​c​t​u​a​l​l​y​ ​w​o​r​k​.​ ​T​h​e​ ​o​n​l​y​ ​e​x​c​e​p​t​i​o​n​ ​i​s​ ​s​k​i​l​l​ ​+​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​,​ ​w​h​e​r​e​ ​t​h​e​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​(​l​i​k​e​ ​"​1​d​4​"​)​ ​w​i​l​l​ ​b​e​ ​a​d​d​e​d​ ​o​n​t​o​ ​t​h​e​ ​s​k​i​l​l
				 */
				expandedDescription: string
				interactions: {
					/**
					 * Y​i​p​!​ ​{​c​h​a​r​a​c​t​e​r​N​a​m​e​}​ ​i​s​ ​a​l​r​e​a​d​y​ ​i​n​ ​t​h​i​s​ ​i​n​i​t​i​a​t​i​v​e​!
					 * @param {unknown} characterName
					 */
					characterAlreadyInInit: RequiredParams<'characterName'>
					joinedEmbed: {
						/**
						 * {​c​h​a​r​a​c​t​e​r​N​a​m​e​}​ ​ ​j​o​i​n​e​d​ ​I​n​i​t​i​a​t​i​v​e​!
						 * @param {unknown} characterName
						 */
						title: RequiredParams<'characterName'>
						/**
						 * I​n​i​t​i​a​t​i​v​e​:​ ​{​i​n​i​t​V​a​l​u​e​}
						 * @param {unknown} initValue
						 */
						setDescription: RequiredParams<'initValue'>
						/**
						 * r​o​l​l​e​d​ ​i​n​i​t​i​a​t​i​v​e​!
						 */
						rollDescription: string
						roundField: {
							/**
							 * ​
							 */
							name: string
							/**
							 * [​I​n​i​t​i​a​t​i​v​e​ ​R​o​u​n​d​ ​{​c​u​r​r​e​n​t​R​o​u​n​d​}​]​(​{​u​r​l​}​)
							 * @param {unknown} currentRound
							 * @param {unknown} url
							 */
							value: RequiredParams<'currentRound' | 'url'>
						}
					}
				}
			}
			add: {
				/**
				 * a​d​d
				 */
				name: string
				/**
				 * [​n​a​m​e​]​ ​[​*​d​i​c​e​*​]​ ​[​*​v​a​l​u​e​*​]
				 */
				options: string
				/**
				 * _​[​n​a​m​e​]​_​:​ ​T​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​s​k​i​l​l​ ​(​"​p​e​r​c​e​p​t​i​o​n​"​)​ ​t​o​ ​u​s​e​ ​t​o​ ​j​o​i​n​ ​i​n​i​t​i​a​t​i​v​e​.​
			​_​[​*​d​i​c​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​T​h​e​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​(​"​1​d​2​0​+​5​"​)​ ​t​o​ ​u​s​e​ ​t​o​ ​j​o​i​n​ ​i​n​i​t​i​a​t​i​v​e​.​
			​_​[​*​v​a​l​u​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​T​h​e​ ​s​t​a​t​i​c​ ​v​a​l​u​e​ ​(​"​1​5​"​)​ ​t​o​ ​u​s​e​ ​t​o​ ​j​o​i​n​ ​i​n​i​t​i​a​t​i​v​e​.
				 */
				usage: string
				/**
				 * A​d​d​s​ ​a​n​ ​N​P​C​ ​o​r​ ​m​i​n​i​o​n​ ​t​o​ ​i​n​i​t​i​a​t​i​v​e
				 */
				description: string
				/**
				 * A​d​d​s​ ​a​ ​m​i​n​i​o​n​ ​w​i​t​h​ ​t​h​e​ ​p​r​o​v​i​d​e​d​ ​n​a​m​e​ ​t​o​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​.​ ​I​f​ ​n​o​ ​o​p​t​i​o​n​s​ ​a​r​e​ ​p​r​o​v​i​d​e​d​,​ ​a​ ​f​l​a​t​ ​d​2​0​ ​i​s​ ​r​o​l​l​e​d​ ​f​o​r​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​v​a​l​u​e​.​ ​I​f​ ​b​o​t​h​ ​d​i​c​e​ ​a​n​d​ ​a​ ​v​a​l​u​e​ ​a​r​e​ ​p​r​o​v​i​d​e​d​,​ ​o​n​l​y​ ​t​h​e​ ​f​l​a​t​ ​v​a​l​u​e​ ​w​i​l​l​ ​a​c​t​u​a​l​l​y​ ​w​o​r​k​.​ ​T​h​i​s​ ​c​h​a​r​a​c​t​e​r​ ​i​s​ ​c​o​n​t​r​o​l​l​e​d​ ​b​y​ ​t​h​e​ ​p​l​a​y​e​r​ ​w​h​o​ ​a​d​d​e​d​ ​i​t​ ​t​o​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​.​
			​
			​N​o​t​e​,​ ​n​a​m​e​s​ ​i​n​ ​i​n​i​t​i​a​t​i​v​e​ ​a​r​e​ ​u​n​i​q​u​e​,​ ​a​d​d​i​n​g​ ​a​ ​d​u​p​l​i​c​a​t​e​ ​n​a​m​e​ ​w​i​l​l​ ​c​a​u​s​e​ ​a​ ​q​u​a​n​t​i​f​i​e​r​ ​l​i​k​e​ ​-​1​ ​t​o​ ​b​e​ ​a​d​d​e​d​ ​t​o​ ​t​h​e​ ​n​a​m​e​.​ ​e​.​g​.​ ​G​o​b​l​i​n​-​1​.​ ​i​f​ ​t​h​e​ ​n​a​m​e​ ​G​o​b​l​i​n​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s​.
				 */
				expandedDescription: string
				interactions: {
					joinedEmbed: {
						/**
						 * {​a​c​t​o​r​N​a​m​e​}​ ​r​o​l​l​e​d​ ​i​n​i​t​i​a​t​i​v​e​!
						 * @param {unknown} actorName
						 */
						rolledTitle: RequiredParams<'actorName'>
						/**
						 * {​a​c​t​o​r​N​a​m​e​}​ ​j​o​i​n​e​d​ ​i​n​i​t​i​a​t​i​v​e​!
						 * @param {unknown} actorName
						 */
						joinedTitle: RequiredParams<'actorName'>
						/**
						 * I​n​i​t​i​a​t​i​v​e​:​ ​{​f​i​n​a​l​I​n​i​t​i​a​t​i​v​e​}
						 * @param {unknown} finalInitiative
						 */
						description: RequiredParams<'finalInitiative'>
						roundField: {
							/**
							 * ​
							 */
							name: string
							/**
							 * [​I​n​i​t​i​a​t​i​v​e​ ​R​o​u​n​d​ ​{​c​u​r​r​e​n​t​R​o​u​n​d​}​]​(​{​u​r​l​}​)
							 * @param {unknown} currentRound
							 * @param {unknown} url
							 */
							value: RequiredParams<'currentRound' | 'url'>
						}
					}
				}
			}
			set: {
				/**
				 * s​e​t
				 */
				name: string
				/**
				 * [​n​a​m​e​]​ ​[​o​p​t​i​o​n​]​ ​[​v​a​l​u​e​]
				 */
				options: string
				/**
				 * _​[​n​a​m​e​]​_​:​ ​T​h​e​ ​n​a​m​e​ ​o​f​ ​a​ ​c​h​a​r​a​c​t​e​r​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​.​
			​_​[​o​p​t​i​o​n​]​_​:​ ​T​h​e​ ​p​r​o​p​e​r​t​y​ ​o​f​ ​t​h​e​ ​c​h​a​r​a​c​t​e​r​ ​t​o​ ​c​h​a​n​g​e​ ​(​j​u​s​t​ ​f​o​r​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​i​n​i​t​i​a​t​i​v​e​!​)​ ​T​h​i​s​ ​c​a​n​ ​b​e​ ​"​i​n​i​t​i​a​t​i​v​e​"​ ​f​o​r​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​v​a​l​u​e​,​ ​o​r​ ​"​n​a​m​e​"​ ​f​o​r​ ​t​h​e​ ​c​h​a​r​a​c​t​e​r​'​s​ ​d​i​s​p​l​a​y​ ​n​a​m​e​ ​w​h​i​l​e​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​.​
			​_​[​v​a​l​u​e​]​_​:​ ​T​h​e​ ​v​a​l​u​e​ ​t​o​ ​s​e​t​ ​t​h​e​ ​p​r​o​p​e​r​t​y​ ​t​o​.
				 */
				usage: string
				/**
				 * S​e​t​s​ ​c​e​r​t​a​i​n​ ​p​r​o​p​e​r​t​i​e​s​ ​o​f​ ​y​o​u​r​ ​c​h​a​r​a​c​t​e​r​ ​f​o​r​ ​i​n​i​t​i​a​t​i​v​e
				 */
				description: string
				/**
				 * S​e​t​s​ ​e​i​t​h​e​r​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​v​a​l​u​e​ ​o​r​ ​c​u​r​r​e​n​t​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​m​a​t​c​h​i​n​g​ ​c​h​a​r​a​c​t​e​r​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​o​r​d​e​r​.​ ​A​n​y​ ​n​a​m​e​ ​c​h​a​n​g​e​s​ ​a​r​e​ ​o​n​l​y​ ​r​e​f​l​e​c​t​e​d​ ​w​i​t​h​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​.​ ​T​h​e​y​ ​d​o​n​'​t​ ​e​f​f​e​c​t​ ​t​h​e​ ​i​m​p​o​r​t​e​d​ ​c​h​a​r​a​c​t​e​r​ ​e​l​s​e​w​h​e​r​e​.
				 */
				expandedDescription: string
				interactions: {
					/**
					 * Y​i​p​!​ ​P​l​e​a​s​e​ ​s​e​n​d​ ​a​ ​v​a​l​i​d​ ​o​p​t​i​o​n​ ​t​o​ ​u​p​d​a​t​e​.
					 */
					invalidOptionError: string
					/**
					 * Y​i​p​!​ ​Y​o​u​ ​c​a​n​'​t​ ​u​s​e​ ​a​n​ ​e​m​p​t​y​ ​n​a​m​e​!
					 */
					emptyNameError: string
					/**
					 * Y​i​p​!​ ​A​ ​c​h​a​r​a​c​t​e​r​ ​w​i​t​h​ ​t​h​a​t​ ​n​a​m​e​ ​i​s​ ​a​l​r​e​a​d​y​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​.
					 */
					nameExistsError: string
					/**
					 * Y​i​p​!​ ​Y​o​u​ ​c​a​n​ ​o​n​l​y​ ​u​p​d​a​t​e​ ​i​n​i​t​i​a​t​i​v​e​ ​w​i​t​h​ ​a​ ​n​u​m​b​e​r​.
					 */
					initNotNumberError: string
					successEmbed: {
						/**
						 * Y​i​p​!​ ​{​a​c​t​o​r​N​a​m​e​}​ ​h​a​d​ ​t​h​e​i​r​ ​{​f​i​e​l​d​T​o​C​h​a​n​g​e​}​ ​s​e​t​ ​t​o​ ​{​n​e​w​F​i​e​l​d​V​a​l​u​e​}​.
						 * @param {unknown} actorName
						 * @param {unknown} fieldToChange
						 * @param {unknown} newFieldValue
						 */
						title: RequiredParams<'actorName' | 'fieldToChange' | 'newFieldValue'>
					}
				}
			}
			remove: {
				/**
				 * r​e​m​o​v​e
				 */
				name: string
				/**
				 * [​n​a​m​e​]
				 */
				options: string
				/**
				 * _​[​n​a​m​e​]​_​:​ ​T​h​e​ ​n​a​m​e​ ​o​f​ ​a​ ​c​h​a​r​a​c​t​e​r​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​.
				 */
				usage: string
				/**
				 * R​e​m​o​v​e​s​ ​a​ ​c​h​a​r​a​c​t​e​r​ ​f​r​o​m​ ​i​n​i​t​i​a​t​i​v​e​.
				 */
				description: string
				/**
				 * R​e​m​o​v​e​s​ ​t​h​e​ ​c​h​a​r​a​c​t​e​r​ ​t​h​a​t​ ​m​a​t​c​h​e​s​ ​t​h​e​ ​g​i​v​e​n​ ​n​a​m​e​ ​f​r​o​m​ ​i​n​i​t​i​a​t​i​v​e
				 */
				expandedDescription: string
				interactions: {
					deletedEmbed: {
						/**
						 * Y​i​p​!​ ​{​a​c​t​o​r​N​a​m​e​}​ ​w​a​s​ ​r​e​m​o​v​e​d​ ​f​r​o​m​ ​i​n​i​t​i​a​t​i​v​e​.
						 * @param {unknown} actorName
						 */
						title: RequiredParams<'actorName'>
					}
				}
			}
			end: {
				/**
				 * e​n​d
				 */
				name: string
				/**
				 * E​n​d​s​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​i​n​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​c​h​a​n​n​e​l​.
				 */
				description: string
				interactions: {
					/**
					 * Y​i​p​!​ ​E​n​d​e​d​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​!
					 */
					success: string
					/**
					 * Y​i​p​!​ ​S​o​m​e​t​h​i​n​g​ ​w​e​n​t​ ​w​r​o​n​g​!
					 */
					error: string
				}
			}
		}
		roll: {
			/**
			 * r​o​l​l
			 */
			name: string
			/**
			 * R​o​l​l​ ​D​i​c​e
			 */
			description: string
			interactions: {
				/**
				 * Y​i​p​!​ ​Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​a​n​y​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​s​!
				 */
				noActiveCharacter: string
				/**
				 * r​o​l​l​e​d​ ​{​d​i​c​e​T​y​p​e​}
				 * @param {unknown} diceType
				 */
				rolledDice: RequiredParams<'diceType'>
			}
			dice: {
				/**
				 * d​i​c​e
				 */
				name: string
				/**
				 * [​d​i​c​e​]​ ​[​*​n​o​t​e​*​]
				 */
				options: string
				/**
				 * _​[​d​i​c​e​]​_​:​ ​T​h​e​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​t​o​ ​r​o​l​l​ ​(​"​1​d​2​0​ ​-​ ​1​d​4​ ​+​ ​3​)​.​ ​U​s​e​s​ ​a​ ​s​i​m​i​l​a​r​ ​s​y​n​t​a​x​ ​t​o​ ​R​o​l​l​2​0​.​
			​_​[​*​n​o​t​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​n​o​t​e​ ​t​o​ ​a​d​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​d​i​c​e​ ​r​o​l​l​.
				 */
				usage: string
				/**
				 * R​o​l​l​s​ ​s​o​m​e​ ​d​i​c​e​.
				 */
				description: string
				interactions: {
					/**
					 * r​o​l​l​e​d​ ​s​o​m​e​ ​d​i​c​e​!
					 */
					rolledDice: string
				}
			}
			skill: {
				/**
				 * s​k​i​l​l
				 */
				name: string
				/**
				 * [​s​k​i​l​l​]​ ​[​*​d​i​c​e​*​]​ ​[​*​n​o​t​e​*​]
				 */
				options: string
				/**
				 * _​[​s​k​i​l​l​]​_​:​ ​T​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​s​k​i​l​l​ ​t​o​ ​r​o​l​l​.​
			​_​[​*​d​i​c​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​t​o​ ​r​o​l​l​ ​(​"​1​d​2​0​ ​-​ ​1​d​4​ ​+​ ​3​"​)​.​ ​A​d​d​e​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​s​k​i​l​l​ ​r​o​l​l​.​ ​A​l​t​e​r​n​a​t​i​v​e​l​y​,​ ​a​ ​s​i​m​p​l​e​ ​m​o​d​i​f​i​e​r​ ​v​a​l​u​e​ ​(​"​5​"​ ​o​r​ ​"​-​3​"​)​.​
			​_​[​*​n​o​t​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​n​o​t​e​ ​t​o​ ​a​d​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​d​i​c​e​ ​r​o​l​l​.
				 */
				usage: string
				/**
				 * r​o​l​l​s​ ​a​ ​s​k​i​l​l​ ​f​o​r​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r
				 */
				description: string
			}
			perception: {
				/**
				 * p​e​r​c​e​p​t​i​o​n
				 */
				name: string
				/**
				 * [​*​d​i​c​e​*​]​ ​[​*​n​o​t​e​*​]
				 */
				options: string
				/**
				 * _​[​*​d​i​c​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​t​o​ ​r​o​l​l​ ​(​"​1​d​2​0​ ​-​ ​1​d​4​ ​+​ ​3​"​)​.​ ​A​d​d​e​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​p​e​r​c​e​p​t​i​o​n​ ​r​o​l​l​.​ ​A​l​t​e​r​n​a​t​i​v​e​l​y​,​ ​a​ ​s​i​m​p​l​e​ ​m​o​d​i​f​i​e​r​ ​v​a​l​u​e​ ​(​"​5​"​ ​o​r​ ​"​-​3​"​)​.​
			​_​[​*​n​o​t​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​n​o​t​e​ ​t​o​ ​a​d​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​d​i​c​e​ ​r​o​l​l​.
				 */
				usage: string
				/**
				 * r​o​l​l​s​ ​p​e​r​c​e​p​t​i​o​n​ ​f​o​r​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r
				 */
				description: string
			}
			save: {
				/**
				 * s​a​v​e
				 */
				name: string
				/**
				 * [​s​a​v​e​]​ ​[​*​d​i​c​e​*​]​ ​[​*​n​o​t​e​*​]
				 */
				options: string
				/**
				 * _​[​s​a​v​e​]​_​:​ ​T​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​s​a​v​i​n​g​ ​t​h​r​o​w​ ​t​o​ ​r​o​l​l​.​
			​_​[​*​d​i​c​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​t​o​ ​r​o​l​l​ ​(​"​1​d​2​0​ ​-​ ​1​d​4​ ​+​ ​3​"​)​.​ ​A​d​d​e​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​s​a​v​e​ ​r​o​l​l​.​ ​A​l​t​e​r​n​a​t​i​v​e​l​y​,​ ​a​ ​s​i​m​p​l​e​ ​m​o​d​i​f​i​e​r​ ​v​a​l​u​e​ ​(​"​5​"​ ​o​r​ ​"​-​3​"​)​.​
			​_​[​*​n​o​t​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​n​o​t​e​ ​t​o​ ​a​d​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​d​i​c​e​ ​r​o​l​l​.
				 */
				usage: string
				/**
				 * r​o​l​l​s​ ​a​ ​s​a​v​i​n​g​ ​t​h​r​o​w​ ​f​o​r​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r
				 */
				description: string
			}
			ability: {
				/**
				 * a​b​i​l​i​t​y
				 */
				name: string
				/**
				 * [​a​b​i​l​i​t​y​]​ ​[​*​d​i​c​e​*​]​ ​[​*​n​o​t​e​*​]
				 */
				options: string
				/**
				 * _​[​a​b​i​l​i​t​y​]​_​:​ ​T​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​a​b​i​l​i​t​y​ ​t​o​ ​r​o​l​l​.​
			​_​[​*​d​i​c​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​t​o​ ​r​o​l​l​ ​(​"​1​d​2​0​ ​-​ ​1​d​4​ ​+​ ​3​"​)​.​ ​A​d​d​e​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​a​b​i​l​i​t​y​ ​r​o​l​l​.​ ​A​l​t​e​r​n​a​t​i​v​e​l​y​,​ ​a​ ​s​i​m​p​l​e​ ​m​o​d​i​f​i​e​r​ ​v​a​l​u​e​ ​(​"​5​"​ ​o​r​ ​"​-​3​"​)​.​
			​_​[​*​n​o​t​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​n​o​t​e​ ​t​o​ ​a​d​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​d​i​c​e​ ​r​o​l​l​.
				 */
				usage: string
				/**
				 * r​o​l​l​s​ ​a​n​ ​a​b​i​l​i​t​y​ ​f​o​r​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r
				 */
				description: string
			}
			attack: {
				/**
				 * a​t​t​a​c​k
				 */
				name: string
				/**
				 * [​a​t​t​a​c​k​]​ ​[​*​a​t​t​a​c​k​_​m​o​d​i​f​i​e​r​*​]​ ​[​*​d​a​m​a​g​e​_​m​o​d​i​f​i​e​r​*​]​ ​[​*​n​o​t​e​*​]
				 */
				options: string
				/**
				 * _​[​a​t​t​a​c​k​]​_​:​ ​T​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​a​t​t​a​c​k​ ​t​o​ ​r​o​l​l​.​
			​_​[​*​a​t​t​a​c​k​\​_​m​o​d​i​f​i​e​r​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​t​o​ ​r​o​l​l​ ​(​"​1​d​2​0​ ​-​ ​1​d​4​ ​+​ ​3​"​)​.​ ​A​d​d​e​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​a​t​t​a​c​k​ ​r​o​l​l​.​ ​A​l​t​e​r​n​a​t​i​v​e​l​y​,​ ​a​ ​s​i​m​p​l​e​ ​m​o​d​i​f​i​e​r​ ​v​a​l​u​e​ ​(​"​5​"​ ​o​r​ ​"​-​3​"​)​.​
			​_​[​*​d​a​m​a​g​e​\​_​m​o​d​i​f​i​e​r​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​t​o​ ​r​o​l​l​ ​(​"​1​d​2​0​ ​-​ ​1​d​4​ ​+​ ​3​"​)​.​ ​A​d​d​e​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​d​a​m​a​g​e​ ​r​o​l​l​.​ ​A​l​t​e​r​n​a​t​i​v​e​l​y​,​ ​a​ ​s​i​m​p​l​e​ ​m​o​d​i​f​i​e​r​ ​v​a​l​u​e​ ​(​"​5​"​ ​o​r​ ​"​-​3​"​)​.​
			​_​[​*​n​o​t​e​*​]​ ​o​p​t​i​o​n​a​l​_​:​ ​A​ ​n​o​t​e​ ​t​o​ ​a​d​d​ ​t​o​ ​t​h​e​ ​e​n​d​ ​o​f​ ​t​h​e​ ​d​i​c​e​ ​r​o​l​l​.
				 */
				usage: string
				/**
				 * r​o​l​l​s​ ​a​n​ ​a​t​t​a​c​k​ ​f​o​r​ ​y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r
				 */
				description: string
				interactions: {
					rollEmbed: {
						/**
						 * a​t​t​a​c​k​e​d​ ​w​i​t​h​ ​t​h​e​i​r​ ​{​a​t​t​a​c​k​N​a​m​e​}​!
						 * @param {unknown} attackName
						 */
						rollDescription: RequiredParams<'attackName'>
						/**
						 * T​o​ ​H​i​t
						 */
						toHit: string
						/**
						 * D​a​m​a​g​e
						 */
						damage: string
					}
				}
			}
		}
	}
	commandOptions: {
		wgUrl: {
			/**
			 * u​r​l
			 */
			name: string
			/**
			 * T​h​e​ ​u​r​l​ ​o​f​ ​y​o​u​r​ ​w​a​n​d​e​r​e​r​'​s​ ​g​u​i​d​e​ ​c​h​a​r​a​c​t​e​r​.
			 */
			description: string
		}
		name: {
			/**
			 * n​a​m​e
			 */
			name: string
			/**
			 * T​h​e​ ​n​a​m​e​ ​o​f​ ​y​o​u​r​ ​w​a​n​d​e​r​e​r​'​s​ ​g​u​i​d​e​ ​c​h​a​r​a​c​t​e​r​.
			 */
			description: string
		}
		id: {
			/**
			 * c​h​a​r​a​c​t​e​r​_​i​d
			 */
			name: string
			/**
			 * T​h​e​ ​i​d​ ​o​f​ ​y​o​u​r​ ​w​a​n​d​e​r​e​r​'​s​ ​g​u​i​d​e​ ​c​h​a​r​a​c​t​e​r​.
			 */
			description: string
		}
		saveChoice: {
			/**
			 * s​a​v​e
			 */
			name: string
			/**
			 * T​h​e​ ​s​a​v​e​ ​t​o​ ​r​o​l​l​.
			 */
			description: string
		}
		skillChoice: {
			/**
			 * s​k​i​l​l
			 */
			name: string
			/**
			 * T​h​e​ ​s​k​i​l​l​ ​t​o​ ​r​o​l​l​.
			 */
			description: string
			overwrites: {
				/**
				 * T​h​e​ ​s​k​i​l​l​ ​t​o​ ​u​s​e​ ​f​o​r​ ​i​n​i​t​i​a​t​i​v​e​ ​i​n​s​t​e​a​d​ ​o​f​ ​p​e​r​c​e​p​t​i​o​n​.
				 */
				initJoinDescription: string
			}
		}
		abilityChoice: {
			/**
			 * a​b​i​l​i​t​y
			 */
			name: string
			/**
			 * T​h​e​ ​a​b​i​l​i​t​y​ ​t​o​ ​r​o​l​l​.
			 */
			description: string
		}
		attackChoice: {
			/**
			 * a​t​t​a​c​k
			 */
			name: string
			/**
			 * T​h​e​ ​a​t​t​a​c​k​ ​t​o​ ​r​o​l​l​.
			 */
			description: string
		}
		rollExpression: {
			/**
			 * d​i​c​e
			 */
			name: string
			/**
			 * T​h​e​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​t​o​ ​r​o​l​l​.​ ​S​i​m​i​l​a​r​ ​t​o​ ​R​o​l​l​2​0​ ​d​i​c​e​ ​r​o​l​l​s​.
			 */
			description: string
			overwrites: {
				/**
				 * D​i​c​e​ ​t​o​ ​r​o​l​l​ ​t​o​ ​j​o​i​n​ ​i​n​i​t​i​a​t​i​v​e​.
				 */
				initAddDescription: string
				/**
				 * D​i​c​e​ ​t​o​ ​r​o​l​l​ ​t​o​ ​j​o​i​n​ ​i​n​i​t​i​a​t​i​v​e​.​ ​M​o​d​i​f​i​e​s​ ​y​o​u​r​ ​s​k​i​l​l​ ​i​f​ ​y​o​u​ ​c​h​o​s​e​ ​a​ ​s​k​i​l​l​.
				 */
				initJoinDescription: string
			}
		}
		rollModifier: {
			/**
			 * m​o​d​i​f​i​e​r
			 */
			name: string
			/**
			 * A​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​t​o​ ​m​o​d​i​f​y​ ​y​o​u​r​ ​r​o​l​l​.​ ​(​e​.​g​.​ ​"​+​ ​1​ ​+​ ​1​d​4​"​)
			 */
			description: string
		}
		attackRollModifier: {
			/**
			 * a​t​t​a​c​k​_​m​o​d​i​f​i​e​r
			 */
			name: string
			/**
			 * A​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​t​o​ ​m​o​d​i​f​y​ ​y​o​u​r​ ​a​t​t​a​c​k​ ​r​o​l​l​.​ ​(​e​.​g​.​ ​"​+​ ​1​ ​+​ ​1​d​4​"​)
			 */
			description: string
		}
		damageRollModifier: {
			/**
			 * d​a​m​a​g​e​_​m​o​d​i​f​i​e​r
			 */
			name: string
			/**
			 * A​ ​d​i​c​e​ ​e​x​p​r​e​s​s​i​o​n​ ​t​o​ ​m​o​d​i​f​y​ ​y​o​u​r​ ​d​a​m​a​g​e​ ​r​o​l​l​.​ ​(​e​.​g​.​ ​"​+​ ​1​ ​+​ ​1​d​4​"​)
			 */
			description: string
		}
		rollNote: {
			/**
			 * n​o​t​e
			 */
			name: string
			/**
			 * A​ ​n​o​t​e​ ​a​b​o​u​t​ ​t​h​e​ ​r​e​a​s​o​n​ ​f​o​r​ ​t​h​e​ ​r​o​l​l​.
			 */
			description: string
		}
		initValue: {
			/**
			 * v​a​l​u​e
			 */
			name: string
			/**
			 * A​ ​v​a​l​u​e​ ​t​o​ ​s​e​t​ ​y​o​u​r​ ​i​n​i​t​i​a​t​i​v​e​ ​t​o​.​ ​O​v​e​r​w​r​i​t​e​s​ ​a​n​y​ ​o​t​h​e​r​ ​i​n​i​t​ ​o​p​t​i​o​n​s​.
			 */
			description: string
		}
		initActor: {
			/**
			 * n​a​m​e
			 */
			name: string
			/**
			 * T​h​e​ ​n​a​m​e​ ​o​f​ ​t​h​e​ ​N​P​C​/​m​i​n​i​o​n​ ​t​o​ ​a​d​d​ ​t​o​ ​i​n​i​t​i​a​t​i​v​e​.
			 */
			description: string
		}
		initCharacter: {
			/**
			 * c​h​a​r​a​c​t​e​r
			 */
			name: string
			/**
			 * A​ ​c​h​a​r​a​c​t​e​r​ ​p​r​e​s​e​n​t​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​.
			 */
			description: string
		}
		setOption: {
			/**
			 * o​p​t​i​o​n
			 */
			name: string
			/**
			 * T​h​e​ ​c​h​a​r​a​c​t​e​r​ ​o​p​t​i​o​n​ ​t​o​ ​a​l​t​e​r​ ​(​o​n​l​y​ ​w​i​t​h​i​n​ ​t​h​i​s​ ​i​n​i​t​i​a​t​i​v​e​)​.
			 */
			description: string
			choices: {
				initiative: {
					/**
					 * i​n​i​t​i​a​t​i​v​e
					 */
					name: string
					/**
					 * i​n​i​t​i​a​t​i​v​e
					 */
					value: string
				}
				actorName: {
					/**
					 * n​a​m​e
					 */
					name: string
					/**
					 * n​a​m​e
					 */
					value: string
				}
			}
		}
		setValue: {
			/**
			 * v​a​l​u​e
			 */
			name: string
			/**
			 * T​h​e​ ​v​a​l​u​e​ ​t​o​ ​s​e​t​ ​t​h​e​ ​o​p​t​i​o​n​ ​t​o​.
			 */
			description: string
		}
	}
	utils: {
		dice: {
			/**
			 * r​o​l​l​e​d​ ​s​o​m​e​ ​d​i​c​e​!
			 */
			rolledDice: string
			/**
			 * r​o​l​l​e​d​ ​{​a​c​t​i​o​n​N​a​m​e​}
			 * @param {unknown} actionName
			 */
			rolledAction: RequiredParams<'actionName'>
			/**
			 * {​r​o​l​l​E​x​p​r​e​s​s​i​o​n​}​
		​{​r​o​l​l​R​e​n​d​e​r​e​d​E​x​p​r​e​s​s​i​o​n​}​
		​ ​t​o​t​a​l​ ​=​ ​`​{​r​o​l​l​T​o​t​a​l​}​`
			 * @param {unknown} rollExpression
			 * @param {unknown} rollRenderedExpression
			 * @param {unknown} rollTotal
			 */
			rollResult: RequiredParams<'rollExpression' | 'rollRenderedExpression' | 'rollTotal'>
			/**
			 * Y​i​p​!​ ​W​e​ ​d​i​d​n​'​t​ ​u​n​d​e​r​s​t​a​n​d​ ​t​h​e​ ​d​i​c​e​ ​r​o​l​l​ ​{​r​o​l​l​E​x​p​r​e​s​s​i​o​n​}​.
			 * @param {unknown} rollExpression
			 */
			diceRollError: RequiredParams<'rollExpression'>
			/**
			 * Y​i​p​!​ ​W​e​ ​d​i​d​n​'​t​ ​u​n​d​e​r​s​t​a​n​d​ ​t​h​e​ ​d​i​c​e​ ​r​o​l​l​.​
		​{​r​o​l​l​E​r​r​o​r​s​}
			 * @param {unknown} rollErrors
			 */
			diceRollOtherErrors: RequiredParams<'rollErrors'>
		}
		initiative: {
			/**
			 * Y​i​p​!​ ​Y​o​u​ ​d​o​n​'​t​ ​h​a​v​e​ ​c​o​n​t​r​o​l​ ​o​f​ ​a​n​y​ ​c​h​a​r​a​c​t​e​r​s​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​ ​m​a​t​c​h​i​n​g​ ​t​h​a​t​ ​n​a​m​e​!
			 */
			characterNameNotFoundError: string
			/**
			 * Y​i​p​!​ ​Y​o​u​r​ ​a​c​t​i​v​e​ ​c​h​a​r​a​c​t​e​r​ ​i​s​n​'​t​ ​i​n​ ​t​h​i​s​ ​i​n​i​t​i​a​t​i​v​e​!
			 */
			activeCharacterNotInInitError: string
			/**
			 * Y​i​p​!​ ​T​h​e​r​e​'​s​ ​n​o​ ​a​c​t​i​v​e​ ​i​n​i​t​i​a​t​i​v​e​ ​i​n​ ​t​h​i​s​ ​c​h​a​n​n​e​l​.
			 */
			noActiveInitError: string
			/**
			 * Y​i​p​!​ ​Y​o​u​ ​c​a​n​ ​o​n​l​y​ ​s​e​n​d​ ​i​n​i​t​i​a​t​i​v​e​ ​c​o​m​m​a​n​d​s​ ​i​n​ ​a​ ​r​e​g​u​l​a​r​ ​s​e​r​v​e​r​ ​c​h​a​n​n​e​l​.
			 */
			initOutsideServerChannelError: string
			/**
			 * Y​i​p​!​ ​I​ ​c​a​n​'​t​ ​g​o​ ​t​o​ ​t​h​e​ ​n​e​x​t​ ​t​u​r​n​ ​w​h​e​n​ ​n​o​ ​o​n​e​ ​i​s​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​!
			 */
			nextTurnInitEmptyError: string
			/**
			 * Y​i​p​!​ ​I​ ​c​a​n​'​t​ ​g​o​ ​t​o​ ​t​h​e​ ​n​e​x​t​ ​t​u​r​n​ ​w​h​e​n​ ​n​o​ ​o​n​e​ ​i​s​ ​i​n​ ​t​h​e​ ​i​n​i​t​i​a​t​i​v​e​!
			 */
			prevTurnInitEmptyError: string
			/**
			 * Y​i​p​!​ ​I​ ​c​a​n​'​t​ ​g​o​ ​t​o​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​t​u​r​n​ ​w​h​e​n​ ​w​e​ ​h​a​v​e​n​'​t​ ​s​t​a​r​t​e​d​ ​i​n​i​t​i​a​t​i​v​e​!
			 */
			prevTurnInitNotStartedError: string
			/**
			 * Y​i​p​!​ ​I​ ​c​a​n​'​t​ ​g​o​ ​t​o​ ​t​h​e​ ​p​r​e​v​i​o​u​s​ ​t​u​r​n​ ​w​h​e​n​ ​i​t​'​s​ ​t​h​e​ ​v​e​r​y​ ​f​i​r​s​t​ ​t​u​r​n​ ​o​f​ ​t​h​e​ ​f​i​r​s​t​ ​r​o​u​n​d​!
			 */
			prevTurnNotPossibleError: string
		}
	}
}

export type TranslationFunctions = {
	terms: {
		/**
		 * Perception
		 */
		perception: () => LocalizedString
	}
	commands: {
		help: {
			/**
			 * help
			 */
			name: () => LocalizedString
			/**
			 * Get help with commands, permissions, FAQ, etc.
			 */
			description: () => LocalizedString
			faq: {
				/**
				 * faq
				 */
				name: () => LocalizedString
				/**
				 * faq
				 */
				value: () => LocalizedString
				/**
				 * Frequently Asked Questions
				 */
				description: () => LocalizedString
				interactions: {
					embed: {
						/**
						 * Frequently Asked Questions
						 */
						title: () => LocalizedString
						/**
						 * https://i.imgur.com/cVOfw8P.png
						 */
						thumbnail: () => LocalizedString
						addToServer: {
							/**
							 * How do I add Kobold to a server?
							 */
							name: () => LocalizedString
							/**
							 * [Invite Kobold to a Discord Server](https://discord.com/oauth2/authorize?client_id=909138081163137094&scope=bot&permissions=532643576896)
							 */
							value: () => LocalizedString
						}
						slashCommands: {
							/**
							 * How do commands work?
							 */
							name: () => LocalizedString
							/**
							 * Kobold uses discord's new slash commands. To use a slash command, type `/` followed by one of Kobold's commands, and then select the command from discord's pop-up. Required command options automatically appear for you to enter. Optional command options may require you to choose the option from discord's pop-up or to tap the right arrow from the options.
					
						See [Discord's explanation](https://support.discord.com/hc/vi/articles/1500000368501-Slash-Commands-FAQ) for more details!
							 */
							value: () => LocalizedString
						}
						commandOptions: {
							/**
							 * Where can I find a list of kobold's commands?
							 */
							name: () => LocalizedString
							/**
							 * Use the command `/help commands`
							 */
							value: () => LocalizedString
						}
						importCharacter: {
							/**
							 * How do I import a wanderer's guide character?
							 */
							name: () => LocalizedString
							/**
							 * go to your character's webpage in wanderer's guide and copy the webpage URL.
					
						Then, start the `/import` command, and enter that URL in the command's url option. It may ask you to authenticate the character. If so, follow the link, complete the instructions, and then `/import` your character's url again.
							 */
							value: () => LocalizedString
						}
						initiative: {
							/**
							 * How does initiative work?
							 */
							name: () => LocalizedString
							/**
							 * To start initiative, use the command `/init start`. An initiative is now running in the current channel, but it doesn't have any members yet. 
					
						To join initiative with your active character, use `/init join`. If, instead, you want to join initiative with an NPCuse `/init add`. You will be required to enter a name, and have options toeither choose an initiative value to have them join on, or to provide a dice expression for them to roll for their initiative value.
							 */
							value: () => LocalizedString
						}
					}
				}
			}
			about: {
				/**
				 * about
				 */
				name: () => LocalizedString
				/**
				 * about
				 */
				value: () => LocalizedString
				/**
				 * Information about the Kobold bot
				 */
				description: () => LocalizedString
				interactions: {
					embed: {
						/**
						 * About Kobold
						 */
						title: () => LocalizedString
						/**
						 * https://i.imgur.com/cVOfw8P.png
						 */
						thumbnail: () => LocalizedString
						/**
						 * Kobold integrates the excellent character management website Wanderer's Guide with discord for play by post pathfinder 2E games.
				
						 */
						description: () => LocalizedString
						authorField: {
							/**
							 * Developed by
							 */
							name: () => LocalizedString
							/**
							 * SignificantOtter#3403
							 */
							value: () => LocalizedString
						}
						featuresField: {
							/**
							 * Features
							 */
							name: () => LocalizedString
							/**
							 * Import characters from Wanderer's Guide
					
						Roll dice for your character's stats
					
						Track characters and NPCs through rounds of initiative
							 */
							value: () => LocalizedString
						}
						linksField: {
							/**
							 * Links
							 */
							name: () => LocalizedString
							/**
							 * [Invite Kobold to a Discord Server](https://discord.com/oauth2/authorize?client_id=909138081163137094&scope=bot&permissions=532643576896)
						[Support Kobold's development through ko-fi](https://ko-fi.com/significantotter)
						[Join Kobold's Support Server on Discord](https://discord.gg/6bS2GM59uj)
						[Follow Kobold's development on Github](https://github.com/significantotter/kobold)
							 */
							value: () => LocalizedString
						}
					}
				}
			}
			commands: {
				/**
				 * commands
				 */
				name: () => LocalizedString
				/**
				 * commands
				 */
				value: () => LocalizedString
				/**
				 * All commands in Kobold
				 */
				description: () => LocalizedString
				interactions: {
					embed: {
						/**
						 * Kobold Commands
						 */
						title: () => LocalizedString
						/**
						 * https://i.imgur.com/cVOfw8P.png
						 */
						thumbnail: () => LocalizedString
					}
				}
			}
			character: {
				/**
				 * character
				 */
				name: () => LocalizedString
				/**
				 * character
				 */
				value: () => LocalizedString
				/**
				 * Help for the /character command
				 */
				description: () => LocalizedString
				interactions: {
					embed: {
						/**
						 * /character Commands
						 */
						title: () => LocalizedString
						/**
						 * https://i.imgur.com/cVOfw8P.png
						 */
						thumbnail: () => LocalizedString
						/**
						 * Character commands all assist with managing imported charactersfrom Wanderer's guide. They allow you to update your character toreflect changes since you imported it, to display your character's sheet, and to switch between multiple active imported characters. Because wanderer's guide requires OAuth access for a character, import/updatecommands may prompt you to authorize Kobold to read your character.
						 */
						description: () => LocalizedString
					}
				}
			}
			init: {
				/**
				 * init
				 */
				name: () => LocalizedString
				/**
				 * init
				 */
				value: () => LocalizedString
				/**
				 * Help for the /init command
				 */
				description: () => LocalizedString
				interactions: {
					embed: {
						/**
						 * /init Commands
						 */
						title: () => LocalizedString
						/**
						 * https://i.imgur.com/cVOfw8P.png
						 */
						thumbnail: () => LocalizedString
						/**
						 * Manages initiative in a channel. 
					 - Create an initiative with /init start.
					 - Use /init join to join initiative with your active character or /init add to add a minion or NPC to initiative.
					 - Begin the initiative with /init next.
					 - When an NPC is defeated, remove it with /init remove.
					 - When it's over, end the initiative with /init end.
						 */
						description: () => LocalizedString
					}
				}
			}
			roll: {
				/**
				 * roll
				 */
				name: () => LocalizedString
				/**
				 * roll
				 */
				value: () => LocalizedString
				/**
				 * Help for the /roll command
				 */
				description: () => LocalizedString
				interactions: {
					embed: {
						/**
						 * /roll Commands
						 */
						title: () => LocalizedString
						/**
						 * https://i.imgur.com/cVOfw8P.png
						 */
						thumbnail: () => LocalizedString
						/**
						 * Rolls some set of dice. This can either be a simple dice roll unrelated to a character in Kobold, or it can be a skill, save, attack, or ability roll. 
				
					Kobold uses a dice rolling syntax similar to that of Roll20. Any dice roll command will have a field where any arbitrary dice expression may be included, allowing flexibility for your rolls.
						 */
						description: () => LocalizedString
					}
				}
			}
		}
		character: {
			/**
			 * character
			 */
			name: () => LocalizedString
			/**
			 * Character management
			 */
			description: () => LocalizedString
			interactions: {
				/**
				 * Yip! You don't have any active characters! Use /import to import one.
				 */
				noActiveCharacter: () => LocalizedString
				/**
				 * Yip! Before you can {action} a character, you need to authenticate it. Give me permission to read your wanderer's guide character by following [this link]({wgBaseUrl}?characterId={charId}). Then, /character/{action} your character again!
				 */
				authenticationRequest: (arg: { action: unknown, charId: unknown, wgBaseUrl: unknown }) => LocalizedString
			}
			'import': {
				/**
				 * import
				 */
				name: () => LocalizedString
				/**
				 * [url]
				 */
				options: () => LocalizedString
				/**
				 * _[url]_: the url of your character sheet from wanderer's guide
				 */
				usage: () => LocalizedString
				/**
				 * Imports a Wanderer's Guide Character
				 */
				description: () => LocalizedString
				/**
				 * Imports a character from the provided url. If the url is accurate, Kobold will make sure it has authorization to read your character from Wanderer's Guide, and then import that character. Otherwise, a link will be provided for you to grant kobold authorization.
		
			 If you're unable to find the character's url, you can alternately just paste their Wanderer's Guide character id into the url field.
				 */
				expandedDescription: () => LocalizedString
				interactions: {
					/**
					 * Yip! I couldn't find the character at the url '{url}'. Check and make sure you copied it over correctly! Or just paste in the character's id value instead.
					 */
					invalidUrl: (arg: { url: unknown }) => LocalizedString
					/**
					 * Yip! {characterName} is already in the system! Did you mean to /update?
					 */
					characterAlreadyExists: (arg: { characterName: unknown }) => LocalizedString
					/**
					 * Yip! I've successfully imported {characterName}!
					 */
					success: (arg: { characterName: unknown }) => LocalizedString
				}
			}
			list: {
				/**
				 * list
				 */
				name: () => LocalizedString
				/**
				 * lists all active characters
				 */
				description: () => LocalizedString
				/**
				 * Displays a list of all characters imported into Kobold. You can check the name of each character and a quick summary of that character's information.
				 */
				expandedDescription: () => LocalizedString
				interactions: {
					/**
					 * Yip! You don't have any characters yet! Use /import to import some!
					 */
					noCharacters: () => LocalizedString
					characterListEmbed: {
						/**
						 * Characters
						 */
						title: () => LocalizedString
						/**
						 * {characterName}{activeText?}
						 */
						characterFieldName: (arg: { activeText?: unknown, characterName: unknown }) => LocalizedString
						/**
						 * Level {level} {heritage} {ancestry} {classes}
						 */
						characterFieldValue: (arg: { ancestry: unknown, classes: unknown, heritage: unknown, level: unknown }) => LocalizedString
					}
				}
			}
			remove: {
				/**
				 * remove
				 */
				name: () => LocalizedString
				/**
				 * removes an already imported character
				 */
				description: () => LocalizedString
				/**
				 * Attempts to remove your currently active character. This has no effect on your character in Wanderer's Guide, Kobold simply forgets about it. 
		
			The command will prompt you if you really wish to remove your character. If you do, you can still import that character back to Kobold in the future.
				 */
				expandedDescription: () => LocalizedString
				interactions: {
					removeConfirmation: {
						/**
						 * Are you sure you want to remove {characterName}?
						 */
						text: (arg: { characterName: unknown }) => LocalizedString
						/**
						 * REMOVE
						 */
						removeButton: () => LocalizedString
						/**
						 * CANCEL
						 */
						cancelButton: () => LocalizedString
						/**
						 * Yip! Character removal request expired.
						 */
						expired: () => LocalizedString
					}
					/**
					 * Yip! I've successfully removed {characterName}! You can import them again at any time.
					 */
					success: (arg: { characterName: unknown }) => LocalizedString
					/**
					 * Yip! Canceled the request to remove {characterName}!
					 */
					cancelled: (arg: { characterName: unknown }) => LocalizedString
				}
			}
			setActive: {
				/**
				 * set-active
				 */
				name: () => LocalizedString
				/**
				 * [name]
				 */
				options: () => LocalizedString
				/**
				 * _[name]_: the name of the character in Kobold to set active
				 */
				usage: () => LocalizedString
				/**
				 * sets a character as the active character
				 */
				description: () => LocalizedString
				/**
				 * Sets the character matching the provided name as your active character. Your active character is the one used for commands like /character sheet, /roll, /init, or /character update.
				 */
				expandedDescription: () => LocalizedString
				interactions: {
					/**
					 * Yip! {characterName} is now your active character!
					 */
					success: (arg: { characterName: unknown }) => LocalizedString
					/**
					 * Yip! I couldn't find a character matching that name! Check what characters you've imported using /character list
					 */
					notFound: () => LocalizedString
				}
			}
			sheet: {
				/**
				 * sheet
				 */
				name: () => LocalizedString
				/**
				 * displays the active character's sheet
				 */
				description: () => LocalizedString
				/**
				 * Displays a character sheet for your currently active character. The displayed stats are provided by wanderer's guide. These stats are used for any dice commands relating to the character.
				 */
				expandedDescription: () => LocalizedString
				interactions: {
					sheet: {
						coreDataField: {
							/**
							 * Level {level} {heritage} {ancestry} {classes}
					
							 */
							name: (arg: { ancestry: unknown, classes: unknown, heritage: unknown, level: unknown }) => LocalizedString
							/**
							 * Max HP `{health}`
						AC `{armorClass}`
						Perception `{perceptionModifier}` (DC {perceptionDC})
						{classes} DC `{classDC}`
						Speed `{speed}`
					
						Background: {background}
							 */
							value: (arg: { armorClass: unknown, background: unknown, classDC: unknown, classes: unknown, health: unknown, perceptionDC: unknown, perceptionModifier: unknown, speed: unknown }) => LocalizedString
						}
						abilitiesField: {
							/**
							 * Abilities
							 */
							name: () => LocalizedString
						}
						savesField: {
							/**
							 * Saves
							 */
							name: () => LocalizedString
						}
						skillsField: {
							/**
							 * Skills
							 */
							name: () => LocalizedString
						}
					}
				}
			}
			update: {
				/**
				 * update
				 */
				name: () => LocalizedString
				/**
				 * updates an already imported character
				 */
				description: () => LocalizedString
				/**
				 * Updates your currently active character with any new information from Wanderer's guide. If some time has passed since you authorized kobold to read that character's information, you may be asked to authenticate again.
				 */
				expandedDescription: () => LocalizedString
				interactions: {
					/**
					 * Yip! I've successfully updated {characterName}!
					 */
					success: (arg: { characterName: unknown }) => LocalizedString
				}
			}
		}
		init: {
			/**
			 * init
			 */
			name: () => LocalizedString
			/**
			 * Initiative Tracking
			 */
			description: () => LocalizedString
			interactions: {
				/**
				 * Yip! You don't have any active characters!
				 */
				noActiveCharacter: () => LocalizedString
			}
			start: {
				/**
				 * start
				 */
				name: () => LocalizedString
				/**
				 * Start initiative in the current channel.
				 */
				description: () => LocalizedString
				/**
				 * Starts initiative in the current channel. Only one initiative can exist in per channel at a time. The player who creates the initiative ismarked as the GM, and can change names, add, and remove any character present in the initiative, not just their own.
				 */
				expandedDescription: () => LocalizedString
				interactions: {
					/**
					 * Yip! You can only start initiative in a normal server channel.
					 */
					notServerChannelError: () => LocalizedString
					/**
					 * Yip! There's already an initiative in this channel. End it before you start a new one!
					 */
					initExistsError: () => LocalizedString
					/**
					 * Yip! Something when wrong when starting your initiative!
					 */
					otherError: () => LocalizedString
				}
			}
			show: {
				/**
				 * show
				 */
				name: () => LocalizedString
				/**
				 * Displays the current initiative order
				 */
				description: () => LocalizedString
			}
			next: {
				/**
				 * next
				 */
				name: () => LocalizedString
				/**
				 * Moves to the next participant in the initiative order
				 */
				description: () => LocalizedString
			}
			prev: {
				/**
				 * prev
				 */
				name: () => LocalizedString
				/**
				 * Moves to the previous participant in the initiative order
				 */
				description: () => LocalizedString
			}
			jumpTo: {
				/**
				 * jump-to
				 */
				name: () => LocalizedString
				/**
				 * [character]
				 */
				options: () => LocalizedString
				/**
				 * _[character]_: The name of a character in the initiative order.
				 */
				usage: () => LocalizedString
				/**
				 * Jumps to a specific participant in the initiative order
				 */
				description: () => LocalizedString
			}
			join: {
				/**
				 * join
				 */
				name: () => LocalizedString
				/**
				 * [*skill*] [*dice*] [*value*]
				 */
				options: () => LocalizedString
				/**
				 * _[*skill*] optional_: The name of the skill ("perception") to use to join initiative.
			_[*dice*] optional_: The dice expression ("1d20+5") to use to join initiative.
			_[*value*] optional_: The static value ("15") to use to join initiative.
				 */
				usage: () => LocalizedString
				/**
				 * Joins initiative with your active character. Defaults to rolling perception.
				 */
				description: () => LocalizedString
				/**
				 * Joins initiative with your active character. If no options are provided, perception is rolled for the initiative value. If multiple options are provided, only one will actually work. The only exception is skill + dice expression, where the dice expression (like "1d4") will be added onto the skill
				 */
				expandedDescription: () => LocalizedString
				interactions: {
					/**
					 * Yip! {characterName} is already in this initiative!
					 */
					characterAlreadyInInit: (arg: { characterName: unknown }) => LocalizedString
					joinedEmbed: {
						/**
						 * {characterName}  joined Initiative!
						 */
						title: (arg: { characterName: unknown }) => LocalizedString
						/**
						 * Initiative: {initValue}
						 */
						setDescription: (arg: { initValue: unknown }) => LocalizedString
						/**
						 * rolled initiative!
						 */
						rollDescription: () => LocalizedString
						roundField: {
							/**
							 * ​
							 */
							name: () => LocalizedString
							/**
							 * [Initiative Round {currentRound}]({url})
							 */
							value: (arg: { currentRound: unknown, url: unknown }) => LocalizedString
						}
					}
				}
			}
			add: {
				/**
				 * add
				 */
				name: () => LocalizedString
				/**
				 * [name] [*dice*] [*value*]
				 */
				options: () => LocalizedString
				/**
				 * _[name]_: The name of the skill ("perception") to use to join initiative.
			_[*dice*] optional_: The dice expression ("1d20+5") to use to join initiative.
			_[*value*] optional_: The static value ("15") to use to join initiative.
				 */
				usage: () => LocalizedString
				/**
				 * Adds an NPC or minion to initiative
				 */
				description: () => LocalizedString
				/**
				 * Adds a minion with the provided name to the initiative. If no options are provided, a flat d20 is rolled for the initiative value. If both dice and a value are provided, only the flat value will actually work. This character is controlled by the player who added it to the initiative.
		
			Note, names in initiative are unique, adding a duplicate name will cause a quantifier like -1 to be added to the name. e.g. Goblin-1. if the name Goblin already exists.
				 */
				expandedDescription: () => LocalizedString
				interactions: {
					joinedEmbed: {
						/**
						 * {actorName} rolled initiative!
						 */
						rolledTitle: (arg: { actorName: unknown }) => LocalizedString
						/**
						 * {actorName} joined initiative!
						 */
						joinedTitle: (arg: { actorName: unknown }) => LocalizedString
						/**
						 * Initiative: {finalInitiative}
						 */
						description: (arg: { finalInitiative: unknown }) => LocalizedString
						roundField: {
							/**
							 * ​
							 */
							name: () => LocalizedString
							/**
							 * [Initiative Round {currentRound}]({url})
							 */
							value: (arg: { currentRound: unknown, url: unknown }) => LocalizedString
						}
					}
				}
			}
			set: {
				/**
				 * set
				 */
				name: () => LocalizedString
				/**
				 * [name] [option] [value]
				 */
				options: () => LocalizedString
				/**
				 * _[name]_: The name of a character in the initiative.
			_[option]_: The property of the character to change (just for the current initiative!) This can be "initiative" for the initiative value, or "name" for the character's display name while in the initiative.
			_[value]_: The value to set the property to.
				 */
				usage: () => LocalizedString
				/**
				 * Sets certain properties of your character for initiative
				 */
				description: () => LocalizedString
				/**
				 * Sets either the initiative value or current name of the matching character in the initiative order. Any name changes are only reflected within the initiative. They don't effect the imported character elsewhere.
				 */
				expandedDescription: () => LocalizedString
				interactions: {
					/**
					 * Yip! Please send a valid option to update.
					 */
					invalidOptionError: () => LocalizedString
					/**
					 * Yip! You can't use an empty name!
					 */
					emptyNameError: () => LocalizedString
					/**
					 * Yip! A character with that name is already in the initiative.
					 */
					nameExistsError: () => LocalizedString
					/**
					 * Yip! You can only update initiative with a number.
					 */
					initNotNumberError: () => LocalizedString
					successEmbed: {
						/**
						 * Yip! {actorName} had their {fieldToChange} set to {newFieldValue}.
						 */
						title: (arg: { actorName: unknown, fieldToChange: unknown, newFieldValue: unknown }) => LocalizedString
					}
				}
			}
			remove: {
				/**
				 * remove
				 */
				name: () => LocalizedString
				/**
				 * [name]
				 */
				options: () => LocalizedString
				/**
				 * _[name]_: The name of a character in the initiative.
				 */
				usage: () => LocalizedString
				/**
				 * Removes a character from initiative.
				 */
				description: () => LocalizedString
				/**
				 * Removes the character that matches the given name from initiative
				 */
				expandedDescription: () => LocalizedString
				interactions: {
					deletedEmbed: {
						/**
						 * Yip! {actorName} was removed from initiative.
						 */
						title: (arg: { actorName: unknown }) => LocalizedString
					}
				}
			}
			end: {
				/**
				 * end
				 */
				name: () => LocalizedString
				/**
				 * Ends the initiative in the current channel.
				 */
				description: () => LocalizedString
				interactions: {
					/**
					 * Yip! Ended the initiative!
					 */
					success: () => LocalizedString
					/**
					 * Yip! Something went wrong!
					 */
					error: () => LocalizedString
				}
			}
		}
		roll: {
			/**
			 * roll
			 */
			name: () => LocalizedString
			/**
			 * Roll Dice
			 */
			description: () => LocalizedString
			interactions: {
				/**
				 * Yip! You don't have any active characters!
				 */
				noActiveCharacter: () => LocalizedString
				/**
				 * rolled {diceType}
				 */
				rolledDice: (arg: { diceType: unknown }) => LocalizedString
			}
			dice: {
				/**
				 * dice
				 */
				name: () => LocalizedString
				/**
				 * [dice] [*note*]
				 */
				options: () => LocalizedString
				/**
				 * _[dice]_: The dice expression to roll ("1d20 - 1d4 + 3). Uses a similar syntax to Roll20.
			_[*note*] optional_: A note to add to the end of the dice roll.
				 */
				usage: () => LocalizedString
				/**
				 * Rolls some dice.
				 */
				description: () => LocalizedString
				interactions: {
					/**
					 * rolled some dice!
					 */
					rolledDice: () => LocalizedString
				}
			}
			skill: {
				/**
				 * skill
				 */
				name: () => LocalizedString
				/**
				 * [skill] [*dice*] [*note*]
				 */
				options: () => LocalizedString
				/**
				 * _[skill]_: The name of the skill to roll.
			_[*dice*] optional_: A dice expression to roll ("1d20 - 1d4 + 3"). Added to the end of the skill roll. Alternatively, a simple modifier value ("5" or "-3").
			_[*note*] optional_: A note to add to the end of the dice roll.
				 */
				usage: () => LocalizedString
				/**
				 * rolls a skill for your active character
				 */
				description: () => LocalizedString
			}
			perception: {
				/**
				 * perception
				 */
				name: () => LocalizedString
				/**
				 * [*dice*] [*note*]
				 */
				options: () => LocalizedString
				/**
				 * _[*dice*] optional_: A dice expression to roll ("1d20 - 1d4 + 3"). Added to the end of the perception roll. Alternatively, a simple modifier value ("5" or "-3").
			_[*note*] optional_: A note to add to the end of the dice roll.
				 */
				usage: () => LocalizedString
				/**
				 * rolls perception for your active character
				 */
				description: () => LocalizedString
			}
			save: {
				/**
				 * save
				 */
				name: () => LocalizedString
				/**
				 * [save] [*dice*] [*note*]
				 */
				options: () => LocalizedString
				/**
				 * _[save]_: The name of the saving throw to roll.
			_[*dice*] optional_: A dice expression to roll ("1d20 - 1d4 + 3"). Added to the end of the save roll. Alternatively, a simple modifier value ("5" or "-3").
			_[*note*] optional_: A note to add to the end of the dice roll.
				 */
				usage: () => LocalizedString
				/**
				 * rolls a saving throw for your active character
				 */
				description: () => LocalizedString
			}
			ability: {
				/**
				 * ability
				 */
				name: () => LocalizedString
				/**
				 * [ability] [*dice*] [*note*]
				 */
				options: () => LocalizedString
				/**
				 * _[ability]_: The name of the ability to roll.
			_[*dice*] optional_: A dice expression to roll ("1d20 - 1d4 + 3"). Added to the end of the ability roll. Alternatively, a simple modifier value ("5" or "-3").
			_[*note*] optional_: A note to add to the end of the dice roll.
				 */
				usage: () => LocalizedString
				/**
				 * rolls an ability for your active character
				 */
				description: () => LocalizedString
			}
			attack: {
				/**
				 * attack
				 */
				name: () => LocalizedString
				/**
				 * [attack] [*attack_modifier*] [*damage_modifier*] [*note*]
				 */
				options: () => LocalizedString
				/**
				 * _[attack]_: The name of the attack to roll.
			_[*attack\_modifier*] optional_: A dice expression to roll ("1d20 - 1d4 + 3"). Added to the end of the attack roll. Alternatively, a simple modifier value ("5" or "-3").
			_[*damage\_modifier*] optional_: A dice expression to roll ("1d20 - 1d4 + 3"). Added to the end of the damage roll. Alternatively, a simple modifier value ("5" or "-3").
			_[*note*] optional_: A note to add to the end of the dice roll.
				 */
				usage: () => LocalizedString
				/**
				 * rolls an attack for your active character
				 */
				description: () => LocalizedString
				interactions: {
					rollEmbed: {
						/**
						 * attacked with their {attackName}!
						 */
						rollDescription: (arg: { attackName: unknown }) => LocalizedString
						/**
						 * To Hit
						 */
						toHit: () => LocalizedString
						/**
						 * Damage
						 */
						damage: () => LocalizedString
					}
				}
			}
		}
	}
	commandOptions: {
		wgUrl: {
			/**
			 * url
			 */
			name: () => LocalizedString
			/**
			 * The url of your wanderer's guide character.
			 */
			description: () => LocalizedString
		}
		name: {
			/**
			 * name
			 */
			name: () => LocalizedString
			/**
			 * The name of your wanderer's guide character.
			 */
			description: () => LocalizedString
		}
		id: {
			/**
			 * character_id
			 */
			name: () => LocalizedString
			/**
			 * The id of your wanderer's guide character.
			 */
			description: () => LocalizedString
		}
		saveChoice: {
			/**
			 * save
			 */
			name: () => LocalizedString
			/**
			 * The save to roll.
			 */
			description: () => LocalizedString
		}
		skillChoice: {
			/**
			 * skill
			 */
			name: () => LocalizedString
			/**
			 * The skill to roll.
			 */
			description: () => LocalizedString
			overwrites: {
				/**
				 * The skill to use for initiative instead of perception.
				 */
				initJoinDescription: () => LocalizedString
			}
		}
		abilityChoice: {
			/**
			 * ability
			 */
			name: () => LocalizedString
			/**
			 * The ability to roll.
			 */
			description: () => LocalizedString
		}
		attackChoice: {
			/**
			 * attack
			 */
			name: () => LocalizedString
			/**
			 * The attack to roll.
			 */
			description: () => LocalizedString
		}
		rollExpression: {
			/**
			 * dice
			 */
			name: () => LocalizedString
			/**
			 * The dice expression to roll. Similar to Roll20 dice rolls.
			 */
			description: () => LocalizedString
			overwrites: {
				/**
				 * Dice to roll to join initiative.
				 */
				initAddDescription: () => LocalizedString
				/**
				 * Dice to roll to join initiative. Modifies your skill if you chose a skill.
				 */
				initJoinDescription: () => LocalizedString
			}
		}
		rollModifier: {
			/**
			 * modifier
			 */
			name: () => LocalizedString
			/**
			 * A dice expression to modify your roll. (e.g. "+ 1 + 1d4")
			 */
			description: () => LocalizedString
		}
		attackRollModifier: {
			/**
			 * attack_modifier
			 */
			name: () => LocalizedString
			/**
			 * A dice expression to modify your attack roll. (e.g. "+ 1 + 1d4")
			 */
			description: () => LocalizedString
		}
		damageRollModifier: {
			/**
			 * damage_modifier
			 */
			name: () => LocalizedString
			/**
			 * A dice expression to modify your damage roll. (e.g. "+ 1 + 1d4")
			 */
			description: () => LocalizedString
		}
		rollNote: {
			/**
			 * note
			 */
			name: () => LocalizedString
			/**
			 * A note about the reason for the roll.
			 */
			description: () => LocalizedString
		}
		initValue: {
			/**
			 * value
			 */
			name: () => LocalizedString
			/**
			 * A value to set your initiative to. Overwrites any other init options.
			 */
			description: () => LocalizedString
		}
		initActor: {
			/**
			 * name
			 */
			name: () => LocalizedString
			/**
			 * The name of the NPC/minion to add to initiative.
			 */
			description: () => LocalizedString
		}
		initCharacter: {
			/**
			 * character
			 */
			name: () => LocalizedString
			/**
			 * A character present in the initiative.
			 */
			description: () => LocalizedString
		}
		setOption: {
			/**
			 * option
			 */
			name: () => LocalizedString
			/**
			 * The character option to alter (only within this initiative).
			 */
			description: () => LocalizedString
			choices: {
				initiative: {
					/**
					 * initiative
					 */
					name: () => LocalizedString
					/**
					 * initiative
					 */
					value: () => LocalizedString
				}
				actorName: {
					/**
					 * name
					 */
					name: () => LocalizedString
					/**
					 * name
					 */
					value: () => LocalizedString
				}
			}
		}
		setValue: {
			/**
			 * value
			 */
			name: () => LocalizedString
			/**
			 * The value to set the option to.
			 */
			description: () => LocalizedString
		}
	}
	utils: {
		dice: {
			/**
			 * rolled some dice!
			 */
			rolledDice: () => LocalizedString
			/**
			 * rolled {actionName}
			 */
			rolledAction: (arg: { actionName: unknown }) => LocalizedString
			/**
			 * {rollExpression}
		{rollRenderedExpression}
		 total = `{rollTotal}`
			 */
			rollResult: (arg: { rollExpression: unknown, rollRenderedExpression: unknown, rollTotal: unknown }) => LocalizedString
			/**
			 * Yip! We didn't understand the dice roll {rollExpression}.
			 */
			diceRollError: (arg: { rollExpression: unknown }) => LocalizedString
			/**
			 * Yip! We didn't understand the dice roll.
		{rollErrors}
			 */
			diceRollOtherErrors: (arg: { rollErrors: unknown }) => LocalizedString
		}
		initiative: {
			/**
			 * Yip! You don't have control of any characters in the initiative matching that name!
			 */
			characterNameNotFoundError: () => LocalizedString
			/**
			 * Yip! Your active character isn't in this initiative!
			 */
			activeCharacterNotInInitError: () => LocalizedString
			/**
			 * Yip! There's no active initiative in this channel.
			 */
			noActiveInitError: () => LocalizedString
			/**
			 * Yip! You can only send initiative commands in a regular server channel.
			 */
			initOutsideServerChannelError: () => LocalizedString
			/**
			 * Yip! I can't go to the next turn when no one is in the initiative!
			 */
			nextTurnInitEmptyError: () => LocalizedString
			/**
			 * Yip! I can't go to the next turn when no one is in the initiative!
			 */
			prevTurnInitEmptyError: () => LocalizedString
			/**
			 * Yip! I can't go to the previous turn when we haven't started initiative!
			 */
			prevTurnInitNotStartedError: () => LocalizedString
			/**
			 * Yip! I can't go to the previous turn when it's the very first turn of the first round!
			 */
			prevTurnNotPossibleError: () => LocalizedString
		}
	}
}

export type Formatters = {}
