// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
	BaseTranslation as BaseTranslationType,
	LocalizedString,
	RequiredParams,
} from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en' | 'en-GB' | 'en-US';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = any;

export type TranslationFunctions = any;

export type Formatters = {};
