/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A single attribute on a sheet
 */
export interface Attribute {
	name: string;
	type: string;
	value: number;
	tags: string[];
	[k: string]: any;
}
