/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A pathfinder npc from the bestiary
 */
export interface Npc {
	/**
	 * The id of the npc record.
	 */
	id: number;
	/**
	 * The pf2etools json data of the npc.
	 */
	data: {
		[k: string]: any;
	};
	/**
	 * The name of the npc.
	 */
	name: string;
	/**
	 * The fluff data of the npc.
	 */
	fluff?: {
		[k: string]: any;
	};
	/**
	 * The name of the npc that serves as the source for this npc's statistics.
	 */
	referenceNpcName: string;
	/**
	 * The name of the source file that the npc was imported from.
	 */
	sourceFileName: string;
	/**
	 * When the character was first imported
	 */
	createdAt?: string;
	/**
	 * When the character was last updated
	 */
	lastUpdatedAt?: string;
	[k: string]: any;
}
