/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An actor group taking part in an initiative
 */
export interface InitiativeActorGroup {
	/**
	 * The id of the initiative actor.
	 */
	id?: number;
	/**
	 * The id of the initiative the actor belongs to.
	 */
	initiativeId?: number;
	/**
	 * The discord id of the user who controls the group
	 */
	userId?: string;
	/**
	 * the name of the group of actors
	 */
	name?: string;
	/**
	 * The initiative result value for the group
	 */
	initiativeResult?: number;
	/**
	 * When the initiative was first started
	 */
	createdAt?: string;
	/**
	 * When the initiative was last interacted with
	 */
	lastUpdatedAt?: string;
	[k: string]: any;
}
