/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A pathfinder creature from the bestiary
 */
export interface Creature {
	/**
	 * The id of the creature record.
	 */
	id?: number;
	/**
	 * The pf2etools json data of the creature.
	 */
	data?: {
		[k: string]: any;
	};
	/**
	 * The name of the source file that the creature was imported from.
	 */
	source_file_name?: string;
	/**
	 * When the character was first imported
	 */
	createdAt?: string;
	/**
	 * When the character was last updated
	 */
	lastUpdatedAt?: string;
	[k: string]: any;
}
