/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An actor taking part in an initiative
 */
export interface InitiativeActor {
	/**
	 * The id of the initiative actor.
	 */
	id?: number;
	/**
	 * The id of the initiative the actor belongs to.
	 */
	initiativeId?: number;
	/**
	 * The id of the initiative actor group the actor belongs to.
	 */
	initiativeActorGroupId?: number;
	/**
	 * The discord id of the user who controls the actor
	 */
	userId?: string;
	/**
	 * The id of the character that this actor represents
	 */
	characterId?: number | null;
	/**
	 * the name of the actor
	 */
	name?: string;
	/**
	 * When the initiative was first started
	 */
	createdAt?: string;
	/**
	 * When the initiative was last interacted with
	 */
	lastUpdatedAt?: string;
	/**
	 * The HP of the initiative actor.
	 */
	hp?: number | null;
	/**
	 * The max HP of the initiative actor.
	 */
	maxHp?: number | null;
	/**
	 * The Stamina Points of the initiative actor.
	 */
	sp?: number | null;
	/**
	 * The max Stamina Points of the initiative actor.
	 */
	maxSp?: number | null;
	/**
	 * The Resolve Points of the initiative actor.
	 */
	rp?: number | null;
	/**
	 * The max Resolve Points of the initiative actor.
	 */
	maxRp?: number | null;
	/**
	 * The Temporary Hit Points of the initiative actor.
	 */
	thp?: number | null;
	[k: string]: any;
}
