/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An actor taking part in an initiative
 */
export interface InitiativeActor {
	/**
	 * The id of the initiative actor.
	 */
	id?: number;
	/**
	 * The id of the initiative the actor belongs to.
	 */
	initiativeId?: number;
	/**
	 * The id of the initiative actor group the actor belongs to.
	 */
	initiativeActorGroupId?: number;
	/**
	 * The discord id of the user who controls the actor
	 */
	userId?: string;
	/**
	 * The id of the character that this actor represents
	 */
	characterId?: number | null;
	/**
	 * The name of the npc that this actor represents
	 */
	referenceNpcName?: string | null;
	/**
	 * the name of the actor
	 */
	name?: string;
	/**
	 * Whether or not to hide the stats of this actor in channel initiative displays
	 */
	hideStats?: boolean;
	/**
	 * When the initiative was first started
	 */
	createdAt?: string;
	/**
	 * When the initiative was last interacted with
	 */
	lastUpdatedAt?: string;
	[k: string]: any;
}
