import { KoboldEmbed } from '../../../utils/kobold-embed-utils.js';
import { CompendiumModel } from '../compendium.model.js';
import _ from 'lodash';
import { SharedParsers } from './compendium-parser-helpers.js';
import { EntryParser } from './compendium-entry-parser.js';
import { AttachmentBuilder } from 'discord.js';
import { parseCreature } from './parsers/creature-parser.js';
import { parseAbility } from './parsers/ability-parser.js';
import { parseAction } from './parsers/action-parser.js';
import { parseAffliction } from './parsers/affliction-parser.js';
import { parseAncestry } from './parsers/ancestry-parser.js';
import { parseArchetype } from './parsers/archetype-parser.js';
import { parseBackground } from './parsers/background-parser.js';
import { parseBook } from './parsers/book-parser.js';
import { parseClassFeature } from './parsers/class-feature-parser.js';
import { parseClass } from './parsers/class-parser.js';
import { parseCompanionAbility } from './parsers/companion-ability-parser.js';
import { parseCondition } from './parsers/condition-parser.js';
import { parseCreatureTemplate } from './parsers/creature-template-parser.js';
import { parseDeity } from './parsers/deity-parser.js';
import { parseDomain } from './parsers/domain-parser.js';
import { parseEidolon } from './parsers/eidolon-parser.js';
import { parseEvent } from './parsers/event-parser.js';
import { parseFamiliar } from './parsers/familiar-parser.js';
import { parseFeat } from './parsers/feat-parser.js';
import { parseGroup } from './parsers/group-parser.js';
import { parseHazard } from './parsers/hazard-parser.js';
import { parseItem } from './parsers/item-parser.js';
import { parseLanguage } from './parsers/language-parser.js';
import { parseOptionalFeature } from './parsers/optional-feature-parser.js';
import { parsePlace } from './parsers/place-parser.js';
import { parseQuickRule } from './parsers/quick-rule-parser.js';
import { parseRitual } from './parsers/ritual-parser.js';
import { parseSkill } from './parsers/skill-parser.js';
import { parseSource } from './parsers/source-parser.js';
import { parseSpell } from './parsers/spell-parser.js';
import { parseSubclassFeature } from './parsers/subclass-feature-parser.js';
import { parseTrait } from './parsers/trait-parser.js';
import { parseVariantRule } from './parsers/variant-rule-parser.js';
import { parseVehicle } from './parsers/vehicle-parser.js';
import { parseCompanion } from './parsers/companion-parser.js';
import { parseVersatileHeritage } from './parsers/versatile-heritage-parser.js';
import { parseFamiliarAbility } from './parsers/familiar-ability-parser.js';
import { parseOrganization } from './parsers/organization-parser.js';
import { parseTable } from './parsers/table-parser.js';
import { parseRelicGift } from './parsers/relic-gift-parser.js';

export class CompendiumEmbedParser {
	public helpers: SharedParsers;
	public embed: KoboldEmbed;
	public files: AttachmentBuilder[];
	constructor(
		public model: CompendiumModel,
		public emojiConverter: { (emoji: string): string }
	) {
		this.embed = new KoboldEmbed();
		this.files = [];
		this.helpers = new SharedParsers(this.model, this.emojiConverter);
	}
	public parseAbility = parseAbility;
	public parseAction = parseAction;
	public parseAffliction = parseAffliction;
	public parseAncestry = parseAncestry;
	public parseArchetype = parseArchetype;
	public parseCreature = parseCreature;
	public parseBackground = parseBackground;
	public parseBook = parseBook;
	public parseClassFeature = parseClassFeature;
	public parseClass = parseClass;
	public parseCompanionAbility = parseCompanionAbility;
	public parseCompanion = parseCompanion;
	public parseCondition = parseCondition;
	public parseCreatureTemplate = parseCreatureTemplate;
	public parseDeity = parseDeity;
	public parseDomain = parseDomain;
	public parseEidolon = parseEidolon;
	public parseEvent = parseEvent;
	public parseFamiliarAbility = parseFamiliarAbility;
	public parseFamiliar = parseFamiliar;
	public parseFeat = parseFeat;
	public parseGroup = parseGroup;
	public parseHazard = parseHazard;
	public parseItem = parseItem;
	public parseLanguage = parseLanguage;
	public parseOptionalFeature = parseOptionalFeature;
	public parseOrganization = parseOrganization;
	public parsePlace = parsePlace;
	public parseQuickRule = parseQuickRule;
	public parseRitual = parseRitual;
	public parseRelicGift = parseRelicGift;
	public parseSkill = parseSkill;
	public parseSource = parseSource;
	public parseSpell = parseSpell;
	public parseSubclassFeature = parseSubclassFeature;
	public parseTable = parseTable;
	public parseTrait = parseTrait;
	public parseVariantRule = parseVariantRule;
	public parseVehicle = parseVehicle;
	public parseVersatileHeritage = parseVersatileHeritage;
}
