/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The settings for a user in Kobold.
 */
export interface UserSettings {
	/**
	 * The discord id of the user.
	 */
	userId?: string;
	[k: string]: any;
}
