/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The settings for a user in Kobold.
 */
export interface UserSettings {
	/**
	 * The discord id of the user.
	 */
	userId?: string;
	/**
	 * When to notify the GM in initiative of the status of characters with hidden stats.
	 */
	initStatsNotification?: "never" | "every_turn" | "every_round" | "whenever_hidden";
	/**
	 * Whether to roll in compact mode.
	 */
	rollCompactMode?: "compact" | "normal";
	/**
	 * How detailed to display inline rolls.
	 */
	inlineRollsDisplay?: "compact" | "detailed";
	[k: string]: any;
}
