const links = {
	thumbnail: 'https://i.imgur.com/cVOfw8P.png',
	docs: 'https://top.gg/bot/909138081163137094',
	donate: 'https://ko-fi.com/significantotter',
	invite: 'https://discord.com/oauth2/authorize?client_id=909138081163137094&scope=bot&permissions=532643576896',
	source: 'https://github.com/significantotter/kobold',
	support: 'https://discord.gg/6bS2GM59uj',
	template: 'https://github.com/KevinNovak/Discord-Bot-TypeScript-Template',
	vote: 'https://top.gg/bot/909138081163137094',
	wanderersGuide: 'https://legacy.wanderersguide.app',
	pathbuilder: 'https://pathbuilder2e.com',
	pf2etools: 'https://pf2etools.com/',
	stream: '',
};
const bot = {
	name: 'Kobold',
	author: 'SignificantOtter#3403',
	description: [
		`Automates Pathfinder 2E play by post, integrated with [Pathbuilder 2E](${links.pathbuilder}), `,
		`[Wanderer's Guide](${links.wanderersGuide}), and [Pf2eTools](${links.pf2etools}).`,
	].join(''),
};

export let refs = {
	bot: { ...bot },
	colors: {
		default: '#0099ff',
		success: '#00ff83',
		warning: '#ffcc66',
		error: '#ff4a4a',
	},
	links,
	embedLinks: {
		donate: `[Support Kobold's development through ko-fi](${links.donate})`,
		invite: `[Invite Kobold to a Discord Server](${links.invite})`,
		source: `[Follow Kobold's development on Github](${links.source})`,
		support: `[Join Kobold's Support Server on Discord](${links.support})`,
		template: `[Built with Kevin Novak's Discord Bot TypeScript Template](${links.template})`,
		vote: `[Vote for Kobold!](${links.vote})`,
		pathbuilder: `[Pathbuilder 2E](https://pathbuilder2e.com)`,
		wanderersGuide: `[Wanderer's Guide](https://legacy.wanderersguide.app)`,
		errorReport: `If you want to report this issue, let my creator know on [my support server](${links.support}).`,
	},
	importantCommands: [
		'**/character import-pathbuilder <json export id>** - import a character from Pathbuilder 2E',
		"**/character import-wanderers-guide <url>** - import a character from Wanderer's Guide",
		'**/character update** - update your character to reflect any changes on the source website',
		'**/character set-default** - set a character as the default for either a server or a channel',
		"**/character sheet** - view your active character's sheet",
		'**/roll dice <dice expression>** - roll some dice!',
		'**/roll skill <skill name>** - roll a skill on your active character',
		'**/help init** - see the help page for the initiative tracker',
		'**/help faq** - see some frequently asked questions about Kobold',
		"**/help commands** - view a full list of Kobold's commands",
	],
	permissions: {
		AddReactions: 'Add Reactions',
		Administrator: 'Administrator',
		AttachFiles: 'Attach Files',
		BanMembers: 'Ban Members',
		ChangeNickname: 'Change Nickname',
		Connect: 'Connect',
		CreateEvents: 'Create Events',
		CreateGuildExpressions: 'Create Guild Expressions',
		CreateInstantInvite: 'Create Invite',
		CreatePrivateThreads: 'Create Private Threads',
		CreatePublicThreads: 'Create Public Threads',
		DeafenMembers: 'Deafen Members',
		EmbedLinks: 'Embed Links',
		KickMembers: 'Kick Members',
		ManageChannels: 'Manage Channel(s)',
		ManageEmojisAndStickers: 'Manage Emoji and Stickers',
		ManageEvents: 'Manage Events',
		ManageGuild: 'Manage Server',
		ManageMessages: 'Manage Messages',
		ManageNicknames: 'Manage Nicknames',
		ManageRoles: 'Manage Roles / Permissions',
		ManageThreads: 'Manage Threads / Posts',
		ManageWebhooks: 'Manage Webhooks',
		MentionEveryone: 'Mention Everyone, Here, and All Roles',
		ModerateMembers: 'Timeout Members',
		MoveMembers: 'Move Members',
		MuteMembers: 'Mute Members',
		PrioritySpeaker: 'Priority Speaker',
		ReadMessageHistory: 'Read Message History',
		RequestToSpeak: 'Request to Speak',
		SendMessages: 'Send Messages / Create Posts',
		SendMessagesInThreads: 'Send Messages in Threads / Posts',
		SendPolls: 'Send Polls',
		SendTTSMessages: 'Send Text-to-Speech Messages',
		Speak: 'Speak',
		Stream: 'Video',
		UseApplicationCommands: 'Use Application Commands',
		UseEmbeddedActivities: 'Use Activities',
		UseExternalEmojis: 'Use External Emoji',
		UseExternalStickers: 'Use External Stickers',
		UseVAD: 'Use Voice Activity',
		ViewAuditLog: 'View Audit Log',
		ViewChannel: 'View Channel(s)',
		ViewGuildInsights: 'View Server Insights',
		ManageGuildExpressions: 'Manage Guild Expressions',
		ViewCreatorMonetizationAnalytics: 'View Creator Monetization Analytics',
		UseSoundboard: 'Use Soundboard',
		UseExternalSounds: 'Use External Sounds',
		SendVoiceMessages: 'Send Voice Messages',
	},
};
